### ISSUE TITLE
Spike: Cruce entre raster para cortar el mapa por área de consulta

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#100]
1. Con el raster de prueba nacional a 30 y 90 mts, recortarlo en caliente (en el query) por el área de consulta, ya no con el polígono como lo tenemos ahorita si no con el raster del área de consulta. Para esto entonces Jaime nos va a pasar el raster de un área de consulta (creo que habíamos quedado que el depto de META) y los raster de pruebas a escala nacional a 30 y 90 metros.

2. Usando los mismos ráster a escala nacional a 30 y 90 metros del punto anterior, hacer el mismo recorte en caliente. Pero en este caso, toca obtener el raster del área de consulta de una capa adicional a escala nacional que nos envió Jaime, la cual está dividida por departamentos y sobre la cual hay que hacer un filtro por el id del departamento.

3. Cargar el raster de prueba ya recortado por el área de consulta (Depto de META) y consultarlo desde el front. Para esto Jaime nos va a pasar este raster ya recortado a 30 y 90 mts.

## Consideraciones
¿Se podría considerar que Jaime entregue los raster de las unidades de consulta para cada caso en particular, por ejemplo para pérdida y persistencia en lugar de tener que hacer el clip en caliente?

Rta: Si, se va a trabajar como el punto 3.

**Comment by cazapatamar** [comment]
Se cargaron los datos enviados por Jaime en la bd de pruebas, microservicio `biotablero_forest`:

Capa de prueba nacional continua a 30 y 90 metros (Raster continuo de pruebas simulando datos de `pérdida y persistencia`)

- geo_raster_forest_lp_30_mts
- geo_raster_forest_lp_90_mts

Capa del área de consulta depto META (Solo limites)

- geo_raster_meta_empty_30_mts
- geo_raster_meta_empty_90_mts

Capa del área de consulta depto META (Raster continuo de pruebas simulando datos de `pérdida y persistencia`)

- geo_raster_meta_continuous_30_mts
- geo_raster_meta_continuous_90_mts

Capa nacional, dividida por departamentos (Sólo límites del área de consulta)

- geo_raster_nal_states_30_mts
- geo_raster_nal_states_90_mts

**Comment by cazapatamar** [comment]
1. Se realizaron las pruebas, apuntando a la bd de desarrollo, intentando hacer una consulta (DBeaver y desde la persistencia en el back) haciendo el cruce entre el raster nacional `geo_raster_forest_lp_90_mts` y el raster con el área de consulta `geo_raster_meta_empty_90_mts`, ambas a 90 metros.

En este caso, ya no se puede usar la función `ST_Clip` ya que esta solo sirve entre raster-polígono. Se hizo la prueba con la función `ST_Interception`, la cual funciona para hacer la intersección de los 2 raster, la cual retorna un arreglo de raster mas pequeños. Para que este resultado pueda ser exportado como PNG, es necesario unirlo en un solo raster, para lo cual se usa la función ST_Union. Los resultados no son favorables ya que al aplicar la union, se queda procesando indefinidamente, se deja mas de 1 hora y no responde o aparece un error por falta de memoria.

2. Dado que la prueba 1 no fue exitosa, la prueba 2 no se pudo realizar.

3. Se hace la consulta para simplemente consultar el raster especifico del area de consulta del departamento de META y generar el PNG pero los tiempos no son favorables. Se demora alrededor de 90 segundos. 

Este tiempo anterior es superior al caso anterior cuando se interceptó el raster nacional a 90 metros (Tener en cuenta que era otro raster mas liviano) con el polígono del área de consulta, en ese caso el tiempo fue aproximadamente de 38 segundos.

**Comment by cazapatamar** [comment]
Confirmar con Jaime por que estos raster que nos envió son tan pesados y si la info real puede ser igual.

**Comment by cazapatamar** [comment]
Se definió cargar la geometría para `pedida y persistencia` en formato shape
