### ISSUE TITLE
Actualizar geometrías de las áreas de consulta

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-scrum#103]
# Descripción
Jaime nos envió las [geometrías](https://drive.google.com/drive/folders/18MK5yMYllmhCdh8mp6LLUr7tYUzXMIod?usp=sharing) actualizadas de las unidades de consulta, las cuales incluirán el total de las mismas en una columna extra.

Se deben actualizar especialmente las tablas:
- geo_basin_subzones
- geo environmental_authorities
- geo_state

# Consideraciones
- Dejar el campo con el id del área de consulta como `gid` (para dejar el mismo estandar del resto de capas shape). Seguramente lo que toca hacer es que al subir la capa por medio de QGIS dejar el campo como `gid` y borrar la `fid`
- En general, verificar que el nombre de los campos sea igual a las anteriores

**Comment by Trjegul84** [comment]
Se modificó de las tablas antiguas agregando `_old` al final de su nombre. Las nuevas tablas tienen el nombre original. Las columnas de las nuevas tablas no coinciden:

| tabla_anterior old           |  version nueva         |
|------------------------------|------------------------|
| id_state/id_ea_/id_subzone  (int) |  geofence_id (varchar)          |
| name /name_subzone           |  geofence_name       |


En todas las tablas nuevas existe una columna que se llama `geofence_type` que indica el tipo de geocerca (states, ea o basin_zubzone).

En `geo_basin_subzones` ya no existen las columnas id_basin, id_zone
En` geo_state`s ya no existe la columna `id_country `(siempre igual a 57)
En `geo_environmental_authorities` ya no existe la columna `id `que es un número entero (No estoy segura de si en realidad se usa).

**Comment by Trjegul84** [comment]
Se realizó el cambio de nombres de columnas en backend para ajustarse a la nueva estructura de las tablas. Se presenta un error en el servicio Forest relacionado con el deprecated binary protected y para descartar que se relacione con este cambio se creó una rama  `feature/connectToOldTables` para conectarse a las tablas antiguas (*_old). Sin embargo, en esa rama se sigue presentando el error.
