### ISSUE TITLE
Cargar datos de vacíos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#104]
### Descripción

Cargar los datos y el raster de vacíos. El raster está listo, es el que envió Cristian, pero los datos Jaime quedó en enviarlos el miércoles 6.

Colocar los raster en la  biotablero-diversity en la tabla georaster

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/104?planning-poker) with ZenHub @alegnaaived @cazapatamar @Trjegul84 @danflop

**Comment by cazapatamar** [comment]
Se carga el raster de vacíos.

Los otros datos están pendientes de revisión por parte de cristian y se espera que se entreguen el Miércoles 06/10/2021
