### ISSUE TITLE
Implementación de backend para Indicadores

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-scrum#107]
Con base a lo encontrado en la tarea [102](https://github.com/PEM-Humboldt/biotablero-scrum/issues/102), seleccionar un servicio y hacer los ajustes necesarios para ser usado desde el módulo de indicadores.

En cualquier caso crear un documento con la información de configuración y credenciales.

### Consideraciones

En caso de seleccionar parse, desplegar los contenedores en una máquina pequeña de EC2

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/107?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84

**Comment by erikasv** [comment]
Después de realizar pruebas de concepto sobre los servicios encontrados en la tarea mencionada, decidimos realizar la implementación en Firebase.

Al ser un producto de google está enlazado a las cuentas institucionales y los miembros del equipo quedaron con acceso al proyecto que se va a utilizar para esta implementación. Se planea tener un correo para el equipo de desarrollo para cuando se deban crear cuentas en otros servicios en futuras ocasiones.

**Comment by erikasv** [comment]
@danflop @alegnaaived Durante esta implementación se encontró que se deben hacer ajustes a los datos que nos envió Margarita inicialmente, quedamos a la espera de la corrección o notificación por parte de ella. Temporalmente se dejó comentado la importación de los datos muckup que se hicieron para la primera implementación.

Se aprovechó para incluir la feature flag para cargar o no el módulo de indicadores.

**Comment by erikasv** [comment]
Se creó un documento con unas explicaciones en la carpeta de microservicios de BioTablero
