### ISSUE TITLE
Crear el script para cargar datos de Indicadores

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-scrum#111]
## Descripción:
Margarita envió los datos de los indicadores y tags para ser cargados a la base de datos.

Los tags deben ser transformados para que se ajusten al modelo de datos creado en firebase, probablemente la mejor opción sea crear un script que se encargue de crear los objetos en firebase.

### Resultado:

Los datos de indicadores y tags cargados en firebase

### Funcionalidad asociada en el Frontend:

Modulo de indicadores

## Consideraciones:
Durante la tarea [107](https://github.com/PEM-Humboldt/biotablero-scrum/issues/107) se detectó que se deben hacer algunos ajustes, verificar estos ajustes antes de cargar los datos.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/111?planning-poker) with ZenHub @alegnaaived @danflop @Trjegul84

**Comment by Trjegul84** [comment]
Se cargaron los datos a firebase mediante un script que se encontró en github adaptado para nuestra configuración de backend. 
Para cargar los datos se requiere armar un archivo json a partir del archivo excel y para obtenerlo fue necesario realizar cambios manualmente porque el archivo excel contenía bastantes errores y problemas para transformarlo: espacios en los inicios y finales de oraciones/párrafos, no tenia comillas en las casillas y estas se deben colocar en las palabras de las listas e identificar las palabras compuestas separadas por espacio (ej. Cambio climático), otro problema es que algunos campos tenían errores con información que no correspondía y fue necesario verificar con equipo y borrar manualmente. Además en campos como goals, cada meta debe separarse por comas y estas metas contienen más de dos palabras y mas de dos metas agrupadas por tipo de meta. Los campos tags, scale y goals deben ser convertidos a arreglo y por eso fueron cambiados mediante regex en un editor para agregar los corchetes  [] entre los datos separados por coma.

Se requiere más tiempo de trabajo para lograr un script completo que tome un archivo excel y lo convierta automáticamente en un archivo json adecuado para cargar mediante el script utilizado. También es importante que el equipo temático provea un archivo con los datos más organizados, depurados y sin errores con una estructura "estándar" de tal manera que no sean necesarios tantos cambio ni procesamiento de las palabras, columnas y celdas de excel.

**Comment by Trjegul84** [comment]
Enlace al [script](https://github.com/ericel/tutoring/tree/main/javascript/json-to-firestore) usado en la importación de datos.
