### ISSUE TITLE
Spike: Más spikes sobre rasters (carga y visualización)

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#112]
### Descripción

Realizar las siguientes pruebas:
1. Los tiempo que toma cargar un raster de 30m para una unidad de consulta ya cortado son aceptables? (previamente se habían hecho pruebas cortando el raster al momento de la consulta y los tiempos no habían sido viables)
2. Revisar los resultados de consultar el raster de 300m, si no eran viables, hacer la prueba cargando el raster ya cortado
3. Cargar más de un raster a la vez en el mapa de BioTablero, en teoría esto se puede, pero hay que verificar si qué tantas modificaciones habría que hacer

### Consideración
- Creo que el componente de `MapViewer` acepta sólo una imagen en este momento
- En el punto 3 considerar cargar dos raster que se sobreponen o dos raster que no se sobreponen

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/112?planning-poker) with ZenHub @alegnaaived @danflop @Trjegul84

**Comment by erikasv** [comment]
@cazapatamar Resultados de los raster ya cortados: Punto 3 de [esta tarea](https://github.com/PEM-Humboldt/biotablero-scrum/issues/100#issuecomment-902814117)

**Comment by cazapatamar** [comment]
Punto 2: Las pruebas ya se habían hecho para 300 metros, sobre un raster a nivel nacional y haciendo el corte a traves de postgis. Los resultados se pueden ver en esta tarea #259.

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/cf2e68c1-42b8-4b81-acac-c23bd50e5ef9)

Se consulta con Jaime y se concluye que los tiempos son aceptables y que no es necesario hacer las pruebas de los raster ya cortados por áreas de consulta para 300 mts.

**Comment by cazapatamar** [comment]
Punto 3: Luego de revisar el código se encuentra que si es posible renderizar multiples raster. Se sube PR para revision del equipo.
