### ISSUE TITLE
Backup de las bases de datos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#115]
Ya que se liberó espacio y se conectó nuevamente el volumen externo al servidor de bases de datos, es necesario:

- Sacar un backup de las bases de datos de BioTablero y guardarlas en dicho volumen.
- Revisar y actualizar diagrama entidad relación de las nuevas bases de datos.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/115?planning-poker) with ZenHub @alegnaaived @cazapatamar @Trjegul84

**Comment by cazapatamar** [comment]
Se generaron los 4 backups de las bases de datos de produccion y se actualizó el modelo ER agregando las nuevas tablas agregadas
