### ISSUE TITLE
Spike: Cambiar consulta de filtros

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#116]
La consulta que se está usando en firebase para aplicar los filtros no es lo deseado, firebase retorna todos los indicadores que tengan cualquiera de los filtros seleccionados, se desea que retorne sólo aquellos que tengan todos los filtros.

La solución ideal es que se pueda aplicar la búsqueda directamente en firebase, incluso si permite crear una función personalizada.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/116?planning-poker) with ZenHub @alegnaaived @cazapatamar @Trjegul84

**Comment by Trjegul84** [comment]
Después de realizar pruebas se observa que:
- La consulta con los operadores 'in' 'array-contains' no funciona comparándola con la variable filtros. Se realizó esta prueba para tratar de hacer una consulta compuesta, pero no es posible realizarla.
- Firebase no tiene una forma para ejecutar consultas IN o AND equivalentes. En los foros recomiendan cambiar el modelo de los datos para poder hacer el tipo de consultas para comparar con un arreglo de elementos. ([Ejemplo](https://stackoverflow.com/questions/35323646/query-arrays-values-with-firebase))
Se podría cambiar el modelo de datos para tener documentos por cada categoría donde los elementos sean referencias a los ids de los indicadores y después buscar una forma de eliminar los resultados repetidos.
- Para una posible solución para un query where in puede  ser ajustar este [script](https://stackoverflow.com/questions/29560088/firebase-equivalent-to-sql-where-in/29564075#29564075) recomendado en stackOv.
- Encontré esta opción para implementar un AND pero es lenguaje Angular y los ejemplos usan la librería [adv-firestore-functions ](https://github.com/jdgamble555/adv-firestore-functions)  que tal vez valdría la pena estudiar más para confirmar si nos puede ayudar al objetivo, sobretodo la sección [SEARCHING](https://github.com/jdgamble555/adv-firestore-functions/blob/master/SEARCHING.md)

Conclusión: 
Hasta el momento no se ha encontrado una forma efectiva para realizar la consulta de los filtros de forma acumulativa y con operador AND.
