### ISSUE TITLE
Actualizar rasters de la seccion de número de especies y vacios

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-scrum#117]
Actualizar raster de la seccion de número de especies y vacios de acuerdo a lo que envió Jaime

Borrar los raster anteriores

Probar funcionalidades que no se vean afectadas y analizar el cambio de calidad de las geometrias

[Número de especies](https://drive.google.com/drive/u/1/folders/1c7LygwVUOkDoxcI9nUYTY92_u0fBdYuR)

[Vacios](https://drive.google.com/drive/u/1/folders/1ARGbEoMwVa60iBfjW3u8TV3GfU3enuoL)

**Comment by erikasv** [comment]
Se actualizaron los raster con aquellos que terminan en `_300` pero parece que se veían mejor antes:
Antes:
![image.png](https://images.zenhubusercontent.com/5c422ae4116ade5d16d9d397/538efed4-3bb0-47f4-9f6f-c407d4b0f663)

Después:
![image.png](https://images.zenhubusercontent.com/5c422ae4116ade5d16d9d397/d1f781fb-4d25-49dc-9b65-e0e93233a47b)

**Comment by erikasv** [comment]
En este momento se dejaron las dos tablas en la base de datos, pero el sitio de pruebas está conectado a los raster viejos
