### ISSUE TITLE
ETL for Bosque Seco shape file

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#12]

**Comment by uamoreno** [comment]
SQL scripts were created to populate the geo_tropical_dry_forest_details table.
Later some alter tables and updates must be done in order to finish this issue.

**Comment by uamoreno** [comment]
Two tables: geo_paramo_details & geo_tropical_dry_forest_details were created to store the related information for each ecosystem  on 2002,2009 and 2012:

`	update geo_paramo_details set protected='Quebrada Honda y Canos Parrado y Buque' where protected='Quebrada Honda';
	alter table geo_paramo_details add column id_protected_area int default null;
	alter table geo_paramo_details add column id_biome_fix int default null;
	alter table geo_paramo_details add column area_type varchar(1) default null;
	
	update geo_paramo_details set id_protected_area=foo.gid from (select geo_protected_areas.* from geo_protected_areas) as foo where foo.name=geo_paramo_details.protected;
	
	alter table geo_paramo_details drop column id_protect;
	alter table geo_paramo_details drop column protected;
	alter table geo_paramo_details drop column category_p;
	alter table geo_paramo_details drop column date_resol;
		
	update geo_paramo_details set id_biome_fix=foo.gid	from (select * from geo_biomes) as foo	where foo.name=geo_paramo_details.biome	and id_biome_fix is null;
	
	update geo_paramo_details set id_biome=id_biome_fix;	
	alter table geo_paramo_details drop column id_biome_fix;	
	alter table geo_paramo_details drop column biome;	
	update geo_paramo_details set area_type='N' where cover like '3.%' or cover like '5.%' or cover like '4.%';
	update geo_paramo_details set area_type='S' where cover like '2.%';
	update geo_paramo_details set area_type='T' where cover like '1.%';

	alter table geo_paramo_details rename column id_sate to id_state;
	alter table geo_paramo_details rename column id_municip to id_municipality;
	alter table geo_paramo_details rename column category_ma to category;
	alter table geo_paramo_details rename column name_ecosy to name;
	alter table geo_paramo_details rename column year_ecosy to year;
	alter table geo_paramo_details rename column id_area to id_basin;`

`alter table geo_tropical_dry_forest_details add column id_protected_area int default null;
alter table geo_tropical_dry_forest_details add column id_biome_fix int default null;
alter table geo_tropical_dry_forest_details add column area_type varchar(1) default null;
update geo_tropical_dry_forest_details set id_protected_area=foo.gid from (select geo_protected_areas.* from geo_protected_areas) as foo where foo.name=geo_tropical_dry_forest_details.protected;
update geo_tropical_dry_forest_details set biome='Zonobioma Alternohigrico Tropical Estribación norte Sierra Nevada de Santa Marta' where biome='Zonobioma Alternohigrico Tropical Estribación norte Sierra Nevada de Santa Mart';  
update geo_tropical_dry_forest_details set id_biome_fix=foo.gid from (select * from geo_biomes) as foo where foo.name=geo_tropical_dry_forest_details.biome and id_biome_fix is null;
select * from geo_tropical_dry_forest_details where id_biome_fix is null;
alter table geo_tropical_dry_forest_details rename column id_municip to id_municipality;
update geo_tropical_dry_forest_details set area_type='N' where cover like '3.%' or cover like '5.%' or cover like '4.%';
update geo_tropical_dry_forest_details set area_type='S' where cover like '2.%';
update geo_tropical_dry_forest_details set area_type='T' where cover like '1.%';
update geo_tropical_dry_forest_details set id_biome=id_biome_fix;
alter table geo_tropical_dry_forest_details rename column id_biome_fix to id_biome;
alter table geo_tropical_dry_forest_details drop column biome;
alter table geo_tropical_dry_forest_details drop column protected;`

A backup was created to contain the latest changes to de BioTablero production database.
