### ISSUE TITLE
Despliegue

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#127]
Desplegar los componentes de BioTablero:

Aplica para cada componente (backend, frontend, gateway)
- Crear los PR a develop y master de la rama release (si la rama release no existe y es encesario, crearla en el gateway)
- Resolver conflictos con master
- Mezclar en master (previa aprobación)
- Actualizar producción (los 3 componentes)
- Habilitar las flags de producción para que queden disponibles las secciones: vacíos (`speciesRecordsGaps`), indicadores (`indicatorsModule`). Todas las demás banderas deben quedar desactivadas.

- Resolver conflictos con develop
- Mezclar en develop (previa aprovación)
- Actualizar el ambiente de staging para que apunte a la rama develop

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/127?planning-poker) with ZenHub @cazapatamar @danflop @Trjegul84 @alegnaaived

**Comment by Trjegul84** [comment]
**OBSERVACIÓN IMPORTANTE:**
Para esta tarea se nos pasó por alto actualizar la base de datos de producción con los nuevos datos de coberturas y vacíos de registros de especies. En las próximas tareas de despliegue se debe incluir esto como primer paso.
