### ISSUE TITLE
Revisar corrimiento en algunas capas de coberturas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#130]
# Descripción

En algunas unidades de consulta se identifica un corrimiento de las capas de cobertura transformada y secundaria (la capa de cobertura Natural se ve bien). Algunas de las unidades en las que se ha identificado este problema son `Corporación Autónoma Regional de la Orinoquía` y `Guainía`.

# Resultado
Diagnóstico del problema e idealmente propuesta de una posible solución

# Consideraciones
- Durante la reunión se identificó que uno de los casos con el problema recibe la capa natural 20px más ancha que las otras dos capas.
- Es posible que el inconveniente sea al momento de cortar el raster, se recomienda revisar la geometría de la unidad de consulta o la operación de corte como tal.
- Daniel recomendó revisar la proyección de las capas

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/130?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84

**Comment by erikasv** [comment]
El problema parece que fue al cargar los raster a la base de datos, al cargar las capas con el parámetros `-C` se resolvió el problema. Ya se ajustaron las instrucciones para incluir el parámetro `-C` para que se cumplan algunas restricciones al momento de la carga.

**Comment by erikasv** [comment]
@cazapatamar @Trjegul84 porfa pegarle una revisadita por si las moscas

**Comment by cazapatamar** [comment]
El problema fue solucionado. Así se ve CORPOORINOQUIA

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/3edffeed-613a-4337-9be9-37be8d6a409b)
