### ISSUE TITLE
Probar carga de rasters de diferentes tamaños

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#134]
# Descripción

Jaime desea que probemos cargar los raster de ecosistemas estratégicos que nos envió inicialmente. Primero creímos que a causa de que tenían diferentes tamaños (dimensiones y extent) no se podían cargar en la misma tabla donde estaban ya cargados los de coberturas nacionales, pero después de otras pruebas parece que el problema estaba relacionado a las restricciones creadas con la primera carga y a las versiones de postigs usadas en las máquinas desde las que se cargaban las capas.

La prueba debería hacerse así:
1. Cargar a una tabla las capas de coberturas nacionales
1. Cargar a esa misma tabla las capas de coberturas de ecosistemas
1. Probar que las consultas sigan saliendo correctamente

# Resultado
Determinar si es posible tener capas de diferentes dimensiones en la misma tabla y que las consultas se realicen correctamente

# Consideraciones
Es preferible realizar esta tarea después de que esté funcional en el front todo lo relacionado con coberturas, para facilitar las pruebas.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/134?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84

**Comment by Trjegul84** [comment]
Se realizó lo siguiente:

1. Se creó un contenedor de postgis version 9.6 con postgis versión 2.5.
2. Se copiaron los datos de las capas de Coberturas Nacionales y Ecosistemas Estrategicos V.1 Multidimensiones del drive al contenedor creado.
3. Se ejecutaron los comandos de raster2pgsql primero sin -C para cargar las capas Nacionales y luego con -a para cargar los rasters SE v1. 
4. Se cambio el código en la persistencia coverage para usar la nueva tabla creada. 
5. Se realizaron pruebas en front y se documentó en [Pruebas Rasters SE Multidimensiones](https://docs.google.com/document/d/1S6NHXe9Vlp0ZocJ8N0sbJLiw4QnYpkqWJBnObIi1AOw/edit?usp=sharing) 

Se observa que los rasters de algunos ecosistemas estratégicos presentan un corrimiento y se ubican fuera del área continental o por fuera del área de consulta. 

6. Se realizó una segunda prueba primero cargando los rasters de SE y luego con -a los de las coverturas nacionales. 

Esta prueba no resulta exitosa porque no se ve ningún y cambio el corrimiento continúa.
