### ISSUE TITLE
Actualizar dependencias

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#138]
Revisar si hay actualizaciones de las dependencias que se puedan aplicar, tanto en el front como en el back. Sólo aplicar las que no rompan nada.

## Consideraciones
Revisar las alertas de dependabot a ver cómo se pueden resolver

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/138?planning-poker) with ZenHub @cazapatamar @danflop @Trjegul84

**Comment by Trjegul84** [comment]
Frontend:
Se actualizaron las dependencias del front que según la salida del comando`  yarn upgrade-interactive` no generaban problemas, de todas formas se revisó el correcto funcionamiento.
Se revisa salida del comando `yarn npm audit --all --recursive` y se observa que hay 17 vulnerabilidades altas y están relacionadas con la librería `react-scripts y` con las dependencias de versión muy muy atrasada en el paquete de monitoreo comunitario.

**Comment by Trjegul84** [comment]
No se actualiza eslint para prevenir problemas en el PR.
No se actualiza apidoc.  
 Las vulnerabilidades del backend de Severidad  moderada, alta y baja todas están relacionadas con la versión del apidoc.

**Comment by cazapatamar** [comment]
Encontré que el problema es a partir de la versión `7.25.0` de la dependencia `eslint-plugin-react`. Dejé la `7.24.0` y dejan de aparecer los warnings.

@erikasv crees que lo podemos dejar así o mejor no actualizar esa dependencia?

**Comment by erikasv** [comment]
gracias @cazapatamar , está bien que lo dejemos en la 7.24.0
