### ISSUE TITLE
Identificar fallo en leyendas de vacíos en registros de especies 

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#143]
# Descripción

Se ha identificado que algunas veces los nombres de las regiones bióticas no están cargando correctamente en la sección de Vacíos en registros de especies (y algunas veces tampoco en Número de especies).

Tratar de identificar la causa de este problema, considerar, entre otras cosas:
- Peticiones asíncronas que no se estén re-renderizando en el compoente
- Resultados mal traídos desde la base de datos

![imagen.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/a2cb018f-9bd2-43f5-9b48-7ca5fc810e3c)

# Resultado
Reproducir el bug y crear una tarea para arreglarlo

**Comment by Trjegul84** [comment]
El error se logra replicar en el ambiente de producción y staging solo algunas veces de la siguiente forma:
>>Consultas>>Seleccionar Unidad de Consulta >> No esperar a que cargue ecosistemas, al contrario, de inmediato pasar a la pestaña de Especies. 
Repetir el proceso con varias unidades. 
Ejemplo:
Depto>Antioquia>Especies>Regresar>Depto>San Andrés>Especies

Solo se logra replicar en algunas ocasiones, en este caso se observa la región en null porque el endpooint esta retornando null.

Se sospecha que existe un problema en el manejo  del estado de Número de especies porque no a veces no se está sincronizado con la respuesta del endpoint.

**Comment by erikasv** [comment]
Tener en cuenta que número de especies require de la geometría del área de consulta.

**Comment by erikasv** [comment]
El problema ocurre porque se está asignando el estado `bioticRegion` dos veces, tanto cuando se resuelve la petición de vacíos, como cuando se resuelve la de concentración. Cuando por casualidad se resuelve primero la de vacíos, luego se sobreescribe con la respuesta de concentración y la respuesta de concentración [no tiene el nombre de la región](https://pem-humboldt.github.io/biotablero-backend/#api-s_richness-Concentration)

**Comment by erikasv** [comment]
El caso de san andres es un caso particular al que también se le debe dar manejo
