### ISSUE TITLE
Probar concurrencia de biab-2.0

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#146]
# Descripción
Utilizar la herramienta [k6](https://k6.io/docs/es/guias-de-prueba/pruebas-de-carga-para-apis/) para dar un estimado de la concurrencia que admite el servidor de biab-2.0

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/146?planning-poker) with ZenHub @ManuelStardust

**Comment by ManuelStardust** [comment]
Se realizaron las pruebas de concurrencia y se obtuvieron buenos resultados en la ejecución de scripts individuales y pipelines. Los resultados se dejan en el siguiente documento: https://docs.google.com/document/d/1Bt2Ysr-NFk5uo9H_ZHrZ9NEU-2qMheQxfQOGIk4p2WA/edit#
