### ISSUE TITLE
Ejecutar de script en biab

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#147]
# Actualizado 02/09

## Descripción
Ya contamos con un script que corre en los locales de Manuel y Erika, pero al intentar ejecutarlo en la infraestructura de biab hubo un problema de permisos al momento de escribir los archivos finales.

Se debe lograr correr el script en la infraestructura de biab y verificar qué respuesta se obtiene del endpoint que ejecuta el script, también tomar nota del tiempo que demora en responder la primera vez que se ejecuta (luego utiliza una caché entonces se demora menos.

## Resultado

- Identificar qué modificaciones habría que realizar a los resultados del script para poder utlizarlos desde biotablero.
- Identificar cuantos tipos de resultados se obtienen a partir de ese script y cuál sería la mejor opción para separarlos (para facilitar el consumo de los mismos desde biotablero), por ejemplo partir el script en dos, uno para los datos alfanuméricos y otro para los raster.

---
#### Descripción

Ejecutar el script de pérdida y persistencia en la infraestructura de biab.

#### Resultado

Resultados de la prueba, inconvenientes que hayan ocurrido, pasos seguidos, etc. 

En caso de que hayan modificaciones de código ponerlas en una rama en el repositorio de biotablero-biab-2.0

**Comment by erikasv** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/147?planning-poker) with ZenHub @ManuelStardust

**Comment by ManuelStardust** [comment]
- Se logro integrar el Script dentro del ambiente de Biab, configurando el archivo .yml de descripción.
- Se hicieron lagunas modificaciones en el script como configurar la ruta del workspace en R.
- Se verificó que el script instala las librerias necesarias en el directorio del servidor para Biab.
- Se veficó que el script lee adecuadamente los archivos complementarios para su ejecución.
- No se logro la completa ejecución con resultados finales debido a errores que presenta el Script.

**Comment by erikasv** [comment]
Jaime nos envió un script actualizado que sí corre en nuestros locales.

En la infraestructura de biab hay problemas con la escritura de los archivos por tema de permisos.

**Comment by ManuelStardust** [comment]
Se consiguio la escritura de archivos de salida en el direcotrio **output**. Sin embargo para fines practicos de uso futuro en Biotablero se omitio la salida en archivos CSV y se creo una variable de salida en Json que muestra la tabla de resultados consolidada.

El script no esta generando datos en las columnas category y area_ha.

El tiempo de ejecución del Script es de 74 segundos. 

Con los últimos cambios en el script solo se obtiene un tipo de resultado de salida.

Se realizaron cambios en el script de R para generar la salida en R y convertir los datos de tipo lista a dataframe y posteriormente a Json.

No fue posible definir la variable de salida como Json por lo cual se configuro como tipo text.
