### ISSUE TITLE
Hacer informe PEER

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#149]
# Descripción

Maria C necesita esto para el 27 de oct. Tener en cuenta los puntos que menciona Mara C en el correo y lo siguiente:

- Los scripts e insumos que se identificaron de parte de Temple
- Las ventajas de usar biab-2.0 para correr estos scripts en lugar de usar un backend en R
- Las pruebas que se han realizado
- Las limitaciones para continuar con la integración (la falta del servidor en azure, @danflop determinar cómo ponemos toda esa parte en el informe)

En cuánto a lo que sigue (qué falta para tener todo integrado), tener en cuenta:
- Poner un servidor con biab-2.0 para ejecutar los scripts
- Hacer la petición desde BioTablero y mostrar los resultados

**Comment by ManuelStardust** [comment]
El reporte generado hace parte de un informe global del proyecto.
Inicialemente, se realizó un borrador en el siguiente archivo: https://docs.google.com/document/d/1ggmtJYS4nAS3-2Sj8anPXHN35ewPWbbTV6kNXr3d-GQ/edit#heading=h.pd7ksm3y9p0m
El resultado final se consigno el numeral 4.2.3. del documento general: https://docs.google.com/document/d/1Zg94B5Dhnn7pHaXkjjtyd8tqQp3Eoc75Hih0mQYOmPE/edit#heading=h.lnxbz9
