### ISSUE TITLE
Determinar si vale la pena continuar con la documentación tipo JSDoc

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#150]
# Descripción y resultado

Determinar si debemos seguir usando la documentación tipo JSDoc en las funciones de los servicios, persistencias y utilitarios del backend (para los servicios en typescript).

# Contexto
Desde que empezamos a usar typescript nos hicimos esa pregunta. Y aunque TypeScript tiene implícita la documentación de los tipos de los parámetros y salidas, estaríamos perdiendo la descripción de los mismos y de la función. Sin embargo, estas son prácticamente repetitivas en todas las capas de los servicios, así que puede no ser tan grave.

Lo ideal es buscar si hay alguna recomendación en términos de buenas prácticas con este tema.

# Consideraciones
- Angela identificó este mensaje de la extensión de TypeScript del code en la función de capas de portafolios: `JSDoc types may be moved to TypeScript types.ts(80004)`. Creo que esto es por la ausencia en el tipo de retorno en la función, pero que está presente en la documentación. Habría que ignorar el mensaje o poner el tipo de retorno en todas las funciones y debe ser igual al de la documentación (pero esto ya está cubierto al asignar el tipo del objeto que retorna la función del servicio).
- Esta tarea debe tener una ventana de tiempo a dedicar y no extenderla.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/150?planning-poker) with Zenhub @cazapatamar @danflop @ManuelStardust @Trjegul84

**Comment by ManuelStardust** [comment]
- [Compare JavaScript JSDoc with TypeScript TSDoc for Documentation](https://javascript.plainenglish.io/compare-javascript-jsdoc-with-typescript-tsdoc-for-documentation-a6984de1f2c5)

**Comment by ManuelStardust** [comment]
**Prueba de Concepto**

Se realizó la prueba con archivos del back y front de biotablero. A continuación se muestra el resultado de la documentación para la función getData del controlador TargetsController en portafolios.

![Captura de pantalla de 2022-11-25 17-14-10.png](https://images.zenhubusercontent.com/62a26471ead9cb678cb12220/27abde68-239e-4334-bfc7-df229cee5d95)

**Comment by ManuelStardust** [comment]
Se decidio agregar trabajar con TSDoc y el plugin de Eslint para typescript para el manejo de la documentación del backend, sin embargo la documentación no se va a generar. En el frontend no se trabajara ya que no cuenta con Eslint instalado.
