### ISSUE TITLE
Levantar el ambiente de biab para biotablero

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#151]
# Descripción y Resultado

Levantar el ambiente de biab para hacer las peticiones del ingreso de polígono.

Seguir las instrucciones de este repositorio [biotablero-biab-2.0](https://github.com/PEM-Humboldt/biotablero-biab-2.0)

**Comment by cazapatamar** [comment]
Se levanta correctamente el ambiente.

El único inconveniente que se encontró fue con el [`Compose plugin`](https://docs.docker.com/compose/install/linux/) ya que no estaba instalado en mi equipo y esta info no está en el README.
