### ISSUE TITLE
Cargar datos de portafolios

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#153]
# Descripción y resultado

Crear la base de datos y cargar los datos para el servicio de portafolios.

# Consideraciones
- Crear una nueva base de datos con su respectivo usuario y contraseña (y documentarlo con los demás servicios)
- Cargar los datos de acuerdo al esquema que se discutió y está documentado en el drive

**Comment by cazapatamar** [comment]
Se cargaron los datos alfanumericos y queda pendiente los rasters
