### ISSUE TITLE
Probar ejecución y resultados de pérdida y persistencia

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#156]
- Agregar al servidor en Azure el código del script de perdida y persistencia cargado al repositorio por el equipo de indicadores y los insumos para el mismo.
- Probar la correcta ejecución del código y las salidas obtenidas.
- Realizar las modificaciones necesarias en los archivos de configuración del script para obtener los resultados desde los end points disponibles en Biab.
- Tomar un poligono generado desde Biotablero y usarlo como parámetro de entrada para la ejecución del script.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/156?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by ManuelStardust** [comment]
Se logró incorporar el script dentro del servidor junto con los insumos correspondientes. Se puede ejecutar en el siguiente end point:
[http://74.235.29.64/script/perdidaPersistencia%3E01_pp.R/run](http://74.235.29.64/script/perdidaPersistencia%3E01_pp.R/run
)
Los párametros de prueba con un poligono en archivo externo son los siguientes:
{
	"dir_wkt_polygon": "/scripts/perdidaPersistencia/input/wkt_polygon_test.txt",
	"epsg_polygon": 3395,
	"dir_colection": "/scripts/perdidaPersistencia/input/ppCollection",
	"resolution": 1000,
	"folder_output": "p_p_studyarea_1000m2"
}
