### ISSUE TITLE
Levantar ambiente de prueba temporal en azure

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#159]
# Descripción y resultado

Levantar un ambiente de prueba en una máquina de azure para el taller de la próxima semana. Se deben levantar todos los componentes, excepto el backend de biab que ya está en otra máquina.

# Consideraciones

No es necesario documentar esta máquina, pues es un ambiente solo para la próxima semana

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/159?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by ManuelStardust** [comment]
Se creó un contenedor en Azure para levantar un ambiente de pruebas de fronted, backend, gateway y bases de datos de Biotablero. 

Se lograron levantar los servicios para front, backend y gateway pero no fue posible tener el ambiente completo corriendo a tiempo debido al tamaño de las bases de datos.
