### ISSUE TITLE
Despliegue de ambiente local de BioTablero

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#163]
Desplegar el ambiente local de BioTablero.

No es necesario levantar bases de datos, pero sí backend, gateway y frontend. Como prerrequisito está la conexión a la vpn y el acceso al gitlab.

# Consideraciones

- Cualquier instrucción que no esté clara u obsoleta se debe ir ajustando en una rama, en cualquiera de los dos repositorios (GitHub o GitLab) y al finalizar el despliegue se debe hacer un PR para actualizar dichas instrucciones

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/163?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by hacheG** [comment]
falta desplegar el servicio de Portafolio, por que la ruta no se reconoce

**Comment by hacheG** [comment]
se escribió un código que da cuenta de la ruta en un entorno windows o linux para así crear la carpeta logs y que se pueda levantar el servicio de portafolio, se considera leer documentación de las funciones que general la ruta absoluta para tener una mejor implementación
