### ISSUE TITLE
Levantar servidor local de STAC

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#165]
# Descripción y resultado

Levantar una instancia local de [stac-fastapi](https://github.com/ReseauBiodiversiteQuebec/stac-fastapi), tener en cuenta que este es un fork de [/stac-utils/stac-fastapi](https://github.com/stac-utils/stac-fastapi).

El repositorio está adecuado para levantar el servidor usando docker, la idea es hacerlo de esta forma, pues seguramente así lo llevaremos a otro servidor. También se debe asegurar la generación de la documentación y si esta es interactiva de alguna forma, debe quedar funcionando.

Se deben documentar los pasos extras que se hayan realizado para poner a funcionar el servidor, adicionalmente al finalizar esta tarea se debe hacer una reunión con el resto del equipo para explicar los pasos seguidos, mostrar el api y la documentación funcionando.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/165?planning-poker) with Zenhub @cazapatamar @hacheG @ManuelStardust

**Comment by hacheG** [comment]
http://192.168.11.78/pem/STAC
