### ISSUE TITLE
Crear plan para usar arvhivos cog

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#166]
# Descripción y resultado

De acuerdo a las explicaciones de Guillaume sobre el uso de archivos cog para el uso desde el STAC (o incluso sin hacer uso del STAC), estos se deben cargar a un servicio de blob storage.

Revisar la [especificación](https://www.cogeo.org/) e identificar las necesidades para poder usar archivos cog en BioTablero (ya sea con o sin el STAC). Hacer una prueba de concepto cargando un tif de los que hemos usado en BioTablero (por ejemplo pérdida y persistencia) a un bucket de blobstorage y disponiéndolo como cog.

Como resultado se espera una lista de pasos para reproducir la prueba y que sirva de instrucciones para replicar en producción. Debe ser un archivo aparte en el repositorio STAC del GitLab

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/166?planning-poker) with Zenhub @cazapatamar @hacheG @ManuelStardust

**Comment by cazapatamar** [comment]
Se realiza una prueba de concepto inicial donde se convirte un raster a formato cog usando unas funciones de GDAL, luego se sube a un container de blob storage dejando el archivo publico y descargable a traves de la URL. Acá quedan las instrucciones usadas y pasos realizados hasta el momento.

Finalmente se intenta llamar el cog desde biotablero usando el componente de leaflet que tenemos actualmente para mostrar los raster llamado ImageOverlay y no se muestra en el mapa. Se hace otra prueba con un PNG en el mismo blob storage y ese si se muestra. Parece que hay que contemplar cambios pasos o procesamientos adicionales para llamar el cog en los componentes actuales de biotablero.

Se hace la prueba desde insomnia al tif cargado en el blob storage y no se puede visualizar la capa, lo cual hace pensar que debe ser necesario hacer algo adicional para poder tener una salida web.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBam9XIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--faba4f57615657c3c3b891c6308a8edfe8dd51c8/imagen.png)

**Comment by erikasv** [comment]
@cazapatamar faltó el enlace a donde quedaron las instrucciones

**Comment by cazapatamar** [comment]
@erikasv listo ya quedó el enlace
