### ISSUE TITLE
Corregir enlace en texto de pérdida y persistencia

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#170]
https://trello.com/c/olGTE15D/24-en-el-texto-de-p%C3%A9rdida-y-persistencia-en-la-frase-proporci%C3%B3n-de-cobertura-de-%C3%A1rboles-hansen-lleva-a-un-archivo-interno-de-revisi

Preguntar a Maria Alejandra cuál de los dos enlaces dejar

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/170?planning-poker) with Zenhub @cazapatamar @hacheG @ManuelStardust

**Comment by hacheG** [comment]
Texto de archivo interno en la base de datos que se quito
biotablero-utils -- forestLP -- meto
https://docs.google.com/document/d/1xJG5a0Hae7KqLtDk_HhXG0oVcSyYsVR_KcXHSHbtZ3c/edit?pli=1#heading=h.m3kd78sw3mws
