### ISSUE TITLE
Agregar texto en metodología de cobertura

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#172]
https://trello.com/c/5WUirxOj/23-deber%C3%ADamos-tener-un-lugar-donde-mostremos-las-homologaciones-de-los-c%C3%B3digos-de-corine-vs-los-que-tenemos-nosotros-nst-porque-las

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/172?planning-poker) with Zenhub @cazapatamar @hacheG @ManuelStardust

**Comment by hacheG** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGhvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a32e7f768ea92a79853e4d10fae3806afd6557de/pantallazoCobertura.png)

esta es la imagen de como se visualiza.
