### ISSUE TITLE
[Spike] Cargar elemento raster al stac

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#174]
# Descripción y resultado

Seguir las [instrucciones](http://192.168.11.78/pem/STAC/blob/master/STAC_SERVER.md) para levantar un servidor STAC localmente y crear una colección.

Luego hacer y documentar la petición para cargar el elemento raster de pérdida y persistencia que se subió como COG al storage de azure.

# Consideraciones
Creo que los datos de que se definen en [esta función](https://github.com/ReseauBiodiversiteQuebec/io-data/blob/main/bqio/stac_item.py#L12) son de ayuda para lograr cargar el item. No es necesario usar el script, pero si lo considera más fácil puede hacerlo.

También puede buscar documentación para cargar items de tipo raster en otras partes y si encuentra algo comentarlo en esta tarea para que @erikasv y @hacheG puedan replicarlo en sus instancias locales

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/174?planning-poker) with Zenhub @cazapatamar @hacheG @ManuelStardust

**Comment by cazapatamar** [comment]
Inicialmente se revisó la [función](https://github.com/ReseauBiodiversiteQuebec/io-data/blob/main/bqio/stac_item.py#L12) sugerida del repo [io-data](https://github.com/ReseauBiodiversiteQuebec/io-data) (Set de herramientas para crear items y catalogos en el STAC de Biodiversité Québec). En esta ruta encontré unos [datasets](https://github.com/ReseauBiodiversiteQuebec/io-data/tree/main/bqio/datasets) que han sido usados para subir info y tomé [uno](https://github.com/ReseauBiodiversiteQuebec/io-data/blob/main/bqio/datasets/GHMI.py) especifico que es facil de entender y se asemeja a lo que necesitamos hacer. Este dataset lo que hace es:

1. Leer un catalogo existente en un archivo catalog.json 
1. Crear una coleccion
1. Subir un tif, convertirlo a COG y subirlo a S3
1. Crear un nuevo item (COG recien subido) y asociarlo a la coleccion
2. Guardar la el catalogo en un archivo de texto

Me salieron algunos errores creo mas por mi desconocimiento en algunos aspectos de Python y la ejecución de ese script entonces decidí tratar de entender mejor que lo estaban haciendo allí por lo que fuí a la documentación de [stacspec](https://stacspec.org/en/) y segui de manera detallada 2 tutoriales relacionados con PySTAC, la misma libreria de Python que usan en los scripts de los datasets y la cual sirve para gestionar todo lo relacionado con los objetos de un catalogo: 

1. Uno para leer y explorar un catalogo
2. Uno para crear un catalogo y agregarle un item (sin colecciones)

Con base en los 2 tutoriales creé un script nuevo para tener una primera aproximación para lo que necesitamos. Tambien tomé algunas cosas del dataset de io-data. Este script lo que hace es:

1. Leer el catalogo que tenemos desplegado localmente (en http://localhost:8082)
2. Imprimir los datos del catalogo y colecciones actuales (Datos de prueba que se subieron con joplin)
3. Leer el COG que tenemos en Azure para obtener el bbox y el footprint (No sé que es)
4. Crear el Item
5. Asociar el Item al catalogo
6. Imprimir los items del catalogo para comprobar que haya quedado guardado
7. Normalizar los HREF para poner la url del catalogo como ruta de todos los objetos
8. Guardar el catalogo en un archivo en el equipo local

A grandes rasgos veo que harian falta 3 cosas para lograr subir un raster como nuevo Item a la coleccion de pruebas que tenemos de manera local:

1. Leer una colección y asociar el Item a la colección y no al catalogo
2. Hacer que el catalogo guardado de manera local se envie al servidor del stac y asi actualizar lo que se tiene allí. En el repo io-data menciona que esto ellos lo hacer con una peticion post a un [endpoint](https://github.com/ReseauBiodiversiteQuebec/io-data#endpoints) pero no logré explorar esa parte.
3. Revisar con mas detalle y quizá tomar como referencia como construyen el Item en el dataset del io-data para verificar que se estan configurando todas las propiedades, entre esas el link al cog ya que en el ejemplo que hice no quedó de esta forma y en el stac de la universidad de quebec está en una seccion del Item llamada `Assets`. En la documentacion me pareción ver algo de eso.

Lo anterior es un avance y se puede usar para terminar este spike en el sigueinte sprint y seria de ayuda tener otra mirada ya que al inicio siento que me bloquee un poco con el uso y ejecución del dataset. Puede que realmente se pueda usar los dataset de ejemplo y no sea dificil y asi poder montar el nuestro. Igualmente creo que la información revisada fue muy util para entender de fondo lo que haca PySTAC.

Dejo en el repo del STAC del gitlab los ejemplos que hice en los tutoriales y el script que hice el cual se llama `addItemToCatalog`.

**Comment by cazapatamar** [comment]
Encontré este [documento](https://github.com/radiantearth/stac-spec/blob/v0.8.1/best-practices.md) con lineamientos de buenas prácticas para montar y administrar un STAC.

Creo que está muy completo y que vale la pena revisarlo en detalle.
