### ISSUE TITLE
Replicar pasos para crear coleccion  y cargar un item (Pasos Camilo)

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-scrum#179]
Seguir los pasos dejados por Camilo en la tarea #174 para crear coleccion y asociar un item

**Comment by ManuelStardust** [comment]
Se consigio seguir los pasos para crear la colección y asociar un item al catálogo. Se verificó que los archivos quedan creados en el directorio local, sin embargo las funciones para consulta del href para el catalogo y el item tienen como resultado false.

Para crar la coleccipon se probo el siguiente código:
 
 `spatial_extent = pystac.SpatialExtent(bboxes=[[-180, -90, 180, 90]])
temporal_extent = pystac.TemporalExtent(intervals=[[datetime.fromisoformat("2016-01-01"),datetime.fromisoformat("2016-12-31")]])
collection_extent = pystac.Extent(spatial=spatial_extent, temporal=temporal_extent)
collection_id = 'ghmts'
collection = pystac.Collection(id=collection_id,
							   title='Global Human Modification of Terrestrial Systems',
                               description='The Global Human Modification of Terrestrial Systems data set provides a cumulative measure of the human modification of terrestrial lands across the globe at a 1-km resolution. It is a continuous 0-1 metric that reflects the proportion of a landscape modified, based on modeling the physical extents of 13 anthropogenic stressors and their estimated impacts using spatially-explicit global data sets with a median year of 2016.',
                               extent=collection_extent,
                               license='CC-BY-SA-4.0',
                               href=collection_id)
root_catalog.add_child(collection)
root_catalog.save(dest_href='/bqio/stac5/',catalog_type=pystac.CatalogType.SELF_CONTAINED)
`
