### ISSUE TITLE
STAC: Agregar opción de subir servicio de almacenamiento en la nube

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-scrum#181]
El repositorio de `io-data` tiene ejemplos de carga de items al STAC donde se hacen algunas cosas que no tenemos aún y que la estamos haciendo por fuera de nuestros scripts:

- Hacer la carga directamente a un servicio de storage, que en nuestro caso es Blobstorage de Azure. Actualmente para el script se asume que el archivo ya se encuentra subido en ese servicio de Blobstorage.

Realizar la revisión y agregar esta opcion a nuestro script (usar el de Erika llamado `/lossPersistence-test/lp.py`) o si es muy complicado establecer una ruta de implementacion y saber que implica tecnicamente.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/181?planning-poker) with Zenhub @ManuelStardust @hacheG

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/181?planning-poker) with Zenhub @hacheG @ManuelStardust

**Comment by ManuelStardust** [comment]
conda install azure-storage-blob azure-identity
