### ISSUE TITLE
STAC: Agregar opción de convertir a COG

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-scrum#182]
El repositorio de `io-data` tiene ejemplos de carga de items al STAC donde se hacen algunas cosas que no tenemos aún y que la estamos haciendo por fuera de nuestros scripts:

- Hacer la conversión a COG directamente en el script. Como lo tenemos actualmente se asume que el raster ya está en formato COG y este proceso se hace por fuera usando las funciones de GDAL. La idea es poder integrar esta lógica en nuestro script de carga.

Realizar la revisión y agregar esta opcion a nuestro script (usar el de Erika llamado `/lossPersistence-test/lp.py`) o si es muy complicado establecer una ruta de implementacion y saber que implica tecnicamente.

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/182?planning-poker) with Zenhub @hacheG @ManuelStardust

**Comment by ManuelStardust** [comment]
[Script Python](https://github.com/harshurampur/Geotiff-conversion)
