### ISSUE TITLE
Replicar los pasos de STAC

### ISSUE THREAD

**Issue by hacheG** [PEM-Humboldt/biotablero-scrum#183]
replicar los pasos que se han seguido para la creación del STAC hechos por Camilo y Erika, siguiendo los pasos de las tareas a continuación:

Camilo: https://github.com/PEM-Humboldt/biotablero-scrum/issues/174

Erika: https://github.com/PEM-Humboldt/biotablero-scrum/issues/176

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/183?planning-poker) with Zenhub @hacheG @ManuelStardust
