### ISSUE TITLE
Prealistamiento release biotablero

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-scrum#184]
Realizar actividades de preparación para el release de biotablero. Algunas pueden ser:

- Listado de objetos de la bd para pasar a producción
- Listado de features nuevos
- Revisar documentación de despliegue (si es necesario)
- Revisar si hay que actualizar feature flags
- Crear etiquea de GA para producción
- Revisar maquina en Azure de biab y determinar si se puede clonar o si toca crear nueva maquina desde 0 (Documentar los pasos)
- Escribir un plan en el orden en el que se deben hacer las cosas y lo que se debería hacer si algo sale mal
- Otras que se consideren necesarias

**Comment by cazapatamar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/184?planning-poker) with Zenhub @erikasv @hacheG @ManuelStardust

**Comment by erikasv** [comment]
Agregaría que se sería bueno escribir un plan en el orden en el que se deben hacer las cosas y lo que se debería hacer si algo sale mal

**Comment by cazapatamar** [comment]
Primera versión del documento

https://docs.google.com/document/d/1Ne1a52ABH8LJSNJaF5JT884De3IpkGM4iwcF2g_Pluk/edit

**Comment by erikasv** [comment]
Como parte de la tarea hay que agregar las nuevas cosas a actualizar o desplegar en la documentación del GitLab en la sección de [Deploy](http://192.168.11.78/pem/BioTablero#deploy) debe quedar el instructivo de cómo sería, de manera que cuando se haga el release sólo sea hacer correcciones.

**Comment by cazapatamar** [comment]
Se geenra este documento con el detalle de este [release](https://docs.google.com/document/d/1Ne1a52ABH8LJSNJaF5JT884De3IpkGM4iwcF2g_Pluk/edit) y la idea es generar uno similar para cada release de aca en adelante.

Adicionalmente se actualizaron las instrucciones del gitlab en donde estan los pasos genéricos
