### ISSUE TITLE
Preparación para el release

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#185]
# Descripción

Se van a adelantar los siguientes pasos para el release:
- [x] Sacar backup de la base de datos main de producción (idealmente solo las tablas relacionadas con Compensaciones)
- [x] Sacar backup de las bases de datos de staging (develop). Guardarlas en su equipo.
- [x] En producción, crear la base de datos para el servicio util como se describe en el [documento del release](https://docs.google.com/document/d/1Ne1a52ABH8LJSNJaF5JT884De3IpkGM4iwcF2g_Pluk/edit#heading=h.bc3mfakkn0ep)
- [x] Crear la etiqueta en la cuenta de GA en producción
- [x] Agregar las variables de GA y del backend de biab a la [configuración del front](http://192.168.11.78/pem/BioTablero/blob/master/frontend-config) guardada en GitLab (o vamos a crear otra máquina para biab, reutilizaremos esta)
- [x] Agregar esas mismas 2 variables (sin valores) al readme del repositorio de [GitHub](https://github.com/PEM-Humboldt/biotablero-frontend?tab=readme-ov-file#14-configuraci%C3%B3n-de-variables-de-entorno)
- [x] Crear un contenedor con la imagen de producción para el front y probar que funcione en la máquina local
- [x] Sacar backup de todas las demás bases de datos de producción

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-scrum/185?planning-poker) with Zenhub @cazapatamar @erikasv @ManuelStardust

**Comment by cazapatamar** [comment]
Se generan todos los pasos de la descripcion y se tienen algunas dudas para ser solucionadas la otra semana. Solo queda pendiente la revision del PR en github con la nueva version del readme y por eso no se cierra la tarea.

**Comment by cazapatamar** [comment]
El MR del gitlab queda [acá](http://192.168.11.78/pem/BioTablero/merge_requests/3)
