### ISSUE TITLE
Levantar STAC localmente

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#189]
# Descripción

Seguir las instrucciones del repositorio del STAC para levantar el servidor localmente. Y usar stac-data-tools para cargar una colección localmente.

# Consideraciones
- Hacer el ejercicio de cargar datos y colección de pruebas como está en el repositorio de GitLab
- Las consideraciones de [este PR](https://github.com/PEM-Humboldt/stac-data-tools/pull/9)
- Las pruebas se pueden realizar con la siguiente colección [lossPersistence](https://drive.google.com/drive/folders/1JFfWeF0XNa9_ZajJ2PYVV8E1S_0LWswx?usp=sharing)

**Comment by denarch22** [comment]
Buen Dia

Durante las pruebas de configuración y ejecución de levantar stac localmente en Windows encontré las siguientes evidencias:

Evidencias instalación STAC DATA TOOLS en Windows

1.	Para subir el stac server y al ejecutar esto: docker compose -f docker-compose-io.yml up, el archivo wait-for-it.sh estaba presentando errores, ya que estaba en formato CR LF de Windows y era necesario dejarlo en LF que es de Linux.
2.	La ruta de ejecución es localhost ya que en la documentación esta 0.0.0.0
3.	Para ejecutar este script de ejemplo: python3 scripts/ingest_joplin.py http://0.0.0.0:8082/ , fue necesario hacerlo con la ruta absoluta ósea desde C: , ya que aunque estuviera en la carpeta no dejaba.
4.	El espacio del ambiente en Conda es necesario especificarle la versión la versión de Python (conda create --name stac-data python=3.10)
5.	Al instalar g-dal fue necesario realizarlo con Conda (conda install -c conda-forge gdal)
6.	Si sigue apareciendo error con g-dal es necesario instalar el paquete por aparte: pip install GDAL-3.7.3-cp310-cp310-win_amd64.whl
7.	El archivo de requirements.txt es necesario instalarlo con Conda (conda install --file requirements.txt)
8.	En el archivo de Stac-data-tools , el .env , es necesario modificar la ruta de la siguiente manera: 
STAC_URL="http://localhost:8082"
