### ISSUE TITLE
Descargar datos de indicadores

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#190]
# Descripción

Descargar todos los datos que están actualmente en la base de datos de indicadores. No se puede hacer un export o backup, por que es de pago.

Descargar las colecciones de `indicadors`, `tags` y `tags_categories`

**Comment by cazapatamar** [comment]
Se crea MR en el GitLab de BioTablero con la logica para generar backup y restore usando nodeJS.

Se dejan los backups generados en JSON en el drive. Se creo una carpeta nueva `Indicadores` dentro de la de Biotablero.
