### ISSUE TITLE
Levantar ambiente local

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#191]
# Descripción

Levantar en la máquina local el ambiente de BioTablero.
[front](https://github.com/PEM-Humboldt/biotablero-frontend)
[backend](https://github.com/PEM-Humboldt/biotablero-backend)
[search-backend](https://github.com/PEM-Humboldt/biotablero-search-backend)

Tener en cuenta lo siguiente:

1. Configurar la VPN
2. Entrar a GitLab interno y actualizar contraseña
3. Seguir las instrucciones de GitHub para levantar los servicios del backend (no clonar las bases de datos, conectarse a las de pruebas). Credenciales u otros datos que no son públicos estarán en el GitLab.
4. Seguir las instrucciones de GitHub para levantar el nuevo backend del módulo de consultas, usar el STAC de azure, en el GitLab está la información.
4. Seguir las instrucciones del GitLab para levantar el Gateway
4. Seguir las instrucciones de GitHub para levantar el frontend. Credenciales u otros datos que no son públicos estarán en el GitLab
5. Conectarse al backend de biab de producción (variable como está en la documentación de GitLab)
5. En caso de que la documentación esté desactualizada en algún repositorio, crear una rama en cada uno y hacer PR / MR para actualizarla.

**Comment by dev-juanzb-humboldt** [comment]
Se crea la configuración de los repos, y proyectos en el local, se hacen pruebas, funciona todo con normalidad, no se presento incidencias.
