### ISSUE TITLE
Group geofences units

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#2]
Create necessary tables.

- Departamentos y municipios
- Subzonas, zonas y cuencas
- Runap
- Ecosistemas estratégicos

**Comment by uamoreno** [comment]
Se ha generado en QGIS el disolve a nivel de departamentos.

**Comment by uamoreno** [comment]
Se han generado en formato shape file las siguientes capas:
geo_states
geo_environmental_authorities
geo_municipalities
geo_basin_areas
geo_basin_zones
geo_basin_subzones
------------------
Quedan pendientes por generar:
tres capas de ecosistemas
Capa RUNAP

**Comment by uamoreno** [comment]
Se han cargado en producción las siguientes capas:

 biotablero | geo_basin_areas                          | tabla     | biotablero | 560 kB     |
 biotablero | geo_basin_subzones                       | tabla     | biotablero | 2832 kB    |
 biotablero | geo_basin_zones                          | tabla     | biotablero | 1392 kB    |
 biotablero | geo_environmental_authorities            | tabla     | biotablero | 4456 kB    |
 biotablero | geo_municipalities                       | tabla     | biotablero | 54 MB      |
 biotablero | geo_paramo                               | tabla     | biotablero | 17 MB      |
 biotablero | geo_protected_areas                      | tabla     | biotablero | 46 MB      |
 biotablero | geo_states                               | tabla     | biotablero | 15 MB      |
 biotablero | geo_tropical_dry_forest                  | tabla     | biotablero | 133 MB     |
 biotablero | geo_wetlands                             | tabla     | biotablero | 17 MB      |

Las tablas geo_basin_* reemplazarían a las tablas: hidro_areas y geo_hidro_areas.
La tabla geo_environmental_authorities reemplazaría a la tabla environmental_authorities.

**Comment by uamoreno** [comment]
Se revisó en la reunión de sprint 2. Se validó la existencia de registros en las tablas de ecosistemas, estas cuentan con el/los registros correspondientes dependiendo del tipo de ecosistema.
