### ISSUE TITLE
Load dissolved geometries for area_type

### ISSUE THREAD

**Issue by uamoreno** [PEM-Humboldt/biotablero-scrum#23]
By solving this issue, 4 shapefiles must be loaded for years 2002, 2009, 2012. 
For a total of 12 shapefiles, on a new table geo_colombia_coverages.
This new table is going to be a features storage consolidating the named years and geofences geometries.

**Comment by uamoreno** [comment]
A pyqgis script was codded to generate different shapes dissolved by main fences.
Later those shape are going to be uploaded into the table geo_ecoystems_by_fences instead of geo_colombia_coverages.

**Comment by uamoreno** [comment]
The dissolves for states, environmental authorities, basins subzones, and protected areas are done for paramos, tropical d.f. and mangroves.

**Comment by erikasv** [comment]
Cuando se actualicen los datos se definirá si esto continua siendo necesario
