### ISSUE TITLE
Discutir y definir atributos y campos de información de HF

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#27]
## Descripción:
Socializar los campos nuevos que se requieren para registrar la información relacionada con HF.

### Resultado:
Conocimiento del estandar de la base de datos y los nombres de las columnas nuevas.

### Funcionalidad asociada en el Frontend:
Todas las gráficas

**Comment by uamoreno** [comment]
Se ha socializado y compartido los nombres de atributos existentes en biotablero como los nuevos.

**Comment by cazapatamar** [comment]
Se realizó la carga inicial de todos los datos de Huella Humana, se compartió el esquema de la base de datos con las nuevas tablas con el equipo funcional de Biotablero. Se cierra esta tarea y si se requieren cambios adicionales sobre las tablas, se crearan nuevas tareas.
