### ISSUE TITLE
Simplificación de las geometrías de HF (years)

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#28]
## Descripción:
Se realiza un proceso de simplificación de las geoemtrías desde QGIS

### Resultado:
Capas shape simplificadas, conservando la mejor relación tamaño-de-arcchivo/detalle del polígono

### Funcionalidad asociada en el Frontend:
Visor de mapas para HF

**Comment by erikasv** [comment]
@danflop , @cazapatamar Deberíamos cerrar esta tarea ya que el año pasado se decidió ceder esta responsabilidad al equipo temático?

**Comment by cazapatamar** [comment]
De acuerdo

**Comment by danflop** [comment]
De acuerdo también. Procedo a cerrar el issue.
