### ISSUE TITLE
Simplificación de las geometrías de HF (years 3)

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-scrum#29]
## Descripción:
Se realiza un proceso de simplificación de las geoemtrías desde QGIS

### Resultado:
Capas shape simplificadas, conservando la mejor relación tamaño-de-achivo/detalle-del-polígono

### Funcionalidad asociada en el Frontend:
Visor de mapas para HF

**Comment by erikasv** [comment]
@cazapatamar , @danflop mismo comentario de la tarea [28](https://app.zenhub.com/workspaces/all-5f7f96a92b54ca00239a9348/issues/pem-humboldt/biotablero-scrum/28)

**Comment by cazapatamar** [comment]
De acuerdo. Creo que no es tan claro aún como vamos a mejorar el desempeño de las capas de huella pero seguramente la solución vendrá desde el equipo temático y no del nuestro.

**Comment by danflop** [comment]
También procedo a cerrar el issue. Sin embargo, debemos tener en cuenta los problemas de rendimiento para discutirlos con el equipo temático en la planeación.
