### ISSUE TITLE
Carga en la base de datos de la información de huella humana actual

### ISSUE THREAD

**Issue by alegnaaived** [PEM-Humboldt/biotablero-scrum#31]
## Descripción:
Importar en la base de datos la información pre calculada para el valor actual de huella humana, discriminada por categorías previamente definidas. Igualmente cargar las geometrías asociadas.

### Resultado:
Tablas o registros en la base de datos con la información solicitada.

### Funcionalidad asociada en el Frontend:
En la pestaña "Paisaje", mostrar gráfico y mapa asociado (Huella humana actual en el área de consulta).

## Consideraciones:
Analizar como el esquema actual para guardar la información en la base de datos se adecúa a la estructura de la información solicitada, o si es necesario crear nuevas tablas, campos, etc.

**Comment by cazapatamar** [comment]
Solucionado en tarea [37](https://app.zenhub.com/workspaces/biotablero-5c423842116ade5d16d9d425/issues/pem-humboldt/biotablero-scrum/37)
