### ISSUE TITLE
Revisión estructura capas HF entregadas

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#34]
## Descripción:
Revisar las capas de HF entregadas por el equipo de Indicadores para encontrar la mejor forma de estructurar esta nueva información e incorporarla en la base de datos actual de BioTablero.

### Resultado:
Decidir sobre la forma en la que se incorporará la información, modificaciones al modelo actual y próximos pasos.

**Comment by erikasv** [comment]
La estructura acordada y la revisión de los datos quedaron condensados en los documentos "Biotablero ER Diagram" (página "20200611 - Reu con Jaime") y "Datos e Información para el Ingreso de la Huella Humana" (sección "Revisión de datos entre las capas entregadas y la base de datos")
