### ISSUE TITLE
Carga en la base de datos de la información de huella humana en el tiempo

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-scrum#36]
## Descripción:
Importar en la base de datos la información pre calculada para el valor de la huella humana en el tiempo, para cada uno de los años previamente definidos. Igualmente cargar las geometrías asociadas.

### Resultado:
Tablas o registros en la base de datos con la información solicitada.

### Funcionalidad asociada en el Frontend:
En la pestaña "Paisaje", mostrar gráfico y mapa asociado (Huella humana en el tiempo en el área de consulta).

## Consideraciones:
Analizar como el esquema actual para guardar la información en la base de datos se adecua a la estructura de la información solicitada, o si es necesario crear nuevas tablas, campos, etc.

**Comment by alegnaaived** [comment]
![image](https://user-images.githubusercontent.com/15584917/85063665-17161c80-b170-11ea-9ed9-69e15461d63c.png)
![image](https://user-images.githubusercontent.com/15584917/85063979-8986fc80-b170-11ea-8b20-cb18ea5380ac.png)

**Comment by alegnaaived** [comment]
![image](https://user-images.githubusercontent.com/15584917/85407705-26f37f00-b529-11ea-9ebb-0831f62f093d.png)
![image](https://user-images.githubusercontent.com/15584917/85408295-f2cc8e00-b529-11ea-9ce3-c517690b517d.png)
![image](https://user-images.githubusercontent.com/15584917/85408343-01b34080-b52a-11ea-9ec9-711f5c105bd1.png)
![image](https://user-images.githubusercontent.com/15584917/85408410-198ac480-b52a-11ea-8143-4f44bb6b1aad.png)
![image](https://user-images.githubusercontent.com/15584917/85408373-0d066c00-b52a-11ea-8181-56dd36de0728.png)
