### ISSUE TITLE
Actualizar nombres de autoridades ambientales

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#38]
En el documento de datos de huella humana se anexó un reporte sobre las diferencias entre los datos entregados en las capas de huella humana y los que ya habían en la base de datos.

Con base a ese reporte, se deben actualizar los nombres de algunas autoridades ambientales en la base de datos.

**Comment by cazapatamar** [comment]
Se cambiaron nombres de acuerdo a este [documento](https://docs.google.com/document/d/1pdV6_xhcXPmZuGQGPwtOW_OpCHujb7JwBqlSeBKYh9w/edit)
