### ISSUE TITLE
Review shape and structure for páramos layer

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#4]
- Review and structure layer data (clean up)

**Comment by uamoreno** [comment]
Se hizo una revisión de las capas recibidas, se prepararon y generaron nuevos shape y los archivos sql con la información de los años 2002, 2009 y 2012, listos para ser cargados en la base de datos.

Se validó con Jaime la razón por la cual los límites de páramos no se modifican año tras año, dónde se identificó que se deja el mismo límite para comparar el cambio de cobertura al interior de este entre natural, transformado y secundario, lo cual se obtiene interpretando el valor del atributo cover.

En la tarea #12  de  actualización del diagrama ER se incluyó la tabla que a futuro contendrá estos datos y que será cargada y ajustada en el desarrollo de la tarea #6
