### ISSUE TITLE
Revisión de tablas entre bases de datos de producción y desarrollo

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#43]
Comparar las tablas entre las bases de datos de producción y desarrollo, y verificar cuales se están consultando desde el Backend

**Comment by cazapatamar** [comment]
Resultado de la revisión:

https://docs.google.com/spreadsheets/d/1MemWhxP0GquC3gyj_LiLT_wPrlttiNKGJUTenZtTPbk/edit#gid=929578545
