### ISSUE TITLE
Spike: Análisis de posible implementación de huella humana como microservicio

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-scrum#46]
Analizar posibles implicaciones de migrar funcionalidad de huella humana a microservicio

- ¿Qué tablas comparte huella humana con otras funcionalidades?
- ¿Qué tablas son exclusivas de huella humana?

**- ¿Cómo orquestar los múltiples microservicios?**
**- ¿Qué tan complicada sería la separación de los servicios relacionados con esta sección?**

Avance

- [x] Camilo
- [x] Erika
- [x] Angela
- [ ] Daniel

Colocar hallazgos como comentarios de esta tarea

**Comment by cazapatamar** [comment]
[Tablas usadas por huella humana](https://docs.google.com/spreadsheets/d/1U3P0TsK7wI32aALuHzY9slBz3FMjoPeLsDwfg-PbZ7o/edit#gid=0)

Conclusión: Huella humana sólo utiliza las 5 tablas creadas para su fin y no se hacen cruces con otras tablas

**Comment by erikasv** [comment]
* Modifiqué la tabla para reflejar todos los servicios que usa cada grupo de endpoints.
* Para separar en un nuevo microservicio me gustaría que intentaramos la estructura de endpoints propuesta en la última columna (new endpoints), este cambio tiene algunas ventajas:
    * Manejamos un sólo endpoint por cada tipo de consulta en lugar de 4
    * No importa el orden de los parámetros areaType, areaId, seType, lo cual ayudará a facilitar la documentación y el uso público del API (cuando sea el momento)
    Podemos controlar los posibles valores para `areaType` y `seType` con estructuras como las de `appropriate_keys`

En cuanto a la separación de la lógica de los servicios no es difícil, pero toca modificarlos casi todos.

**Comment by alegnaaived** [comment]
Mi sugerencia a nivel de front-end serían las siguientes:
 - Se requeriría desplegar de versión más ligera del visor geográfico de BioTablero, para que reciba como parámetros los mapas y no requiera estar en el mismo proyecto de los demás componentes
 - Se requeriría un visor del componente Selector y los flujos de trabajo con sus subcomponentes para permitir las consultas de información de huella humana independientemente de los otros componentes de navegación

**Comment by cazapatamar** [comment]
Podemos cerrar esta tarea? Creo que ya tenemos bastante claro cómo sería esta implementación, las tablas propias de huella humana y la forma de comunicar con el servicio principal. @alegnaaived @danflop @erikasv @Trjegul84

**Comment by erikasv** [comment]
De acuerdo, creo que de migrar puntualmente la sección de huella humana a un microservicio sería por cambio de tecnología, por ahora se aplicará para las siguientes cifras e indicadores.

**Comment by danflop** [comment]
Se cierra puesto que ya se inició la implementación de las nuevas secciones como microservicios.
