### ISSUE TITLE
Update ER diagram with new geo_* tables 

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#5]

**Comment by uamoreno** [comment]
Se realizó el ajuste del diagrama y se redefinieron varias las llaves foráneas con base a las nuevas tablas: geo_environmental_authorities y geo_basin_subzones:

-- eliminar llaves foráneas anteriores
alter table public.geo_compensation_strategies_2018 drop constraint "gcs2018_id_sz_fk";
alter table public.project_impacted_biomes drop constraint "pib_id_sz_fk";
alter table public.selected_strategies drop constraint "ss_id_sz_fk";
alter TABLE "ea_biotic_units" drop CONSTRAINT "ebu_id_ea_fk"; 
alter TABLE "geo_compensation_strategies_2018" drop constraint "gcs2018_id_ea_fk";
alter TABLE "geo_ea_biomes" drop CONSTRAINT "gea_id_ea_fk";
alter TABLE "project_ea_biomes" drop CONSTRAINT "peb_id_ea_fk";
alter TABLE "project_impacted_biomes" drop CONSTRAINT "pib_id_ea_fk";
alter TABLE "selected_strategies" drop CONSTRAINT "ss_id_ea_fk";
-- crear indices únicos para llaves foráneas nuevas
alter table geo_basin_zones add constraint "gbz_id_z_ui" unique (id_zone);
alter table geo_basin_areas add constraint "gba_id_b_ui" unique (id_basin);
alter table geo_basin_areas add constraint "gba_id_b_ui" unique (id_basin);
alter table geo_basin_subzones add constraint "gbsz_id_sz_ui" unique (id_subzone);
alter table geo_environmental_authorities add constraint "gea_id_ea_ui" unique (id_ea);
alter table geo_states add constraint "gs_id_st_ui" unique (id_state);
-- Crear llaves foráneas para las relaciones de cuenca, zona y subzona hidrográfica
alter table biotablero.geo_basin_subzones add constraint "gbsz_id_z_fk" foreign key (id_zone) references geo_basin_zones(id_zone);
alter table biotablero.geo_basin_subzones add constraint "gbsz_id_a_fk" foreign key (id_basin) references geo_basin_areas(id_basin);
alter table biotablero.geo_basin_zones add constraint "gbz_id_a_fk" foreign key (id_basin) references geo_basin_areas(id_basin);
-- Crear llaves foráneas para relacionar las zonas hidrográficas con las tablas que tenía relación hidro_areas.
alter table public.geo_compensation_strategies_2018 add constraint "gcs2018_id_sz_fk" foreign key (id_subzone) references geo_basin_subzones(id_subzone);
alter table public.project_impacted_biomes add constraint "pib_id_sz_fk" foreign key (id_subzone) references geo_basin_subzones(id_subzone);
alter table public.selected_strategies add constraint "ss_id_sz_fk" foreign key (id_subzone) references geo_basin_subzones(id_subzone);
-- Crear llaves foráneas para relacionar la nueva tabla geo_environmental_authorities
alter TABLE "ea_biotic_units" add CONSTRAINT "ebu_id_ea_fk" FOREIGN KEY (id_ea) REFERENCES geo_environmental_authorities(id_ea);
alter TABLE "geo_compensation_strategies_2018" add CONSTRAINT "gcs2018_id_ea_fk" FOREIGN KEY (id_ea) REFERENCES geo_environmental_authorities(id_ea);
alter TABLE "geo_ea_biomes" add CONSTRAINT "gea_id_ea_fk" FOREIGN KEY (id_ea) REFERENCES geo_environmental_authorities(id_ea);
alter TABLE "project_ea_biomes" add CONSTRAINT "peb_id_ea_fk" FOREIGN KEY (id_ea) REFERENCES geo_environmental_authorities(id_ea);
alter TABLE "project_impacted_biomes" add CONSTRAINT "pib_id_ea_fk" FOREIGN KEY (id_ea) REFERENCES geo_environmental_authorities(id_ea);
alter TABLE "selected_strategies" add CONSTRAINT "ss_id_ea_fk" FOREIGN KEY (id_ea) REFERENCES geo_environmental_authorities(id_ea);
-- Crear llaves foraneas para relazionar municipios y departamentos
alter TABLE "geo_municipalities" add CONSTRAINT "gm_id_st_fk" FOREIGN KEY (id_state) REFERENCES geo_states(id_state);

Se creo la tabla geo_paramo_details con base a los archivos shape recibidos.
Hace falta que en el back-end se modifiquen los llamados y consultas sobre las tablas hidro_areas y environmental_authorities.
Si bien la información base con la que se creo la información para indicadores no tiene en cuenta las siguientes CARs:
DADMA	Departamento Administrativo Distrital del Medio Ambiente. (Santa Marta)
EPA	Establecimiento Público Ambiental
Estas tampoco se han tomado en cuenta dentro de los datos de estratgias y biomas que se venían trabajando el año pasado (2018).
