### ISSUE TITLE
Crear base de datos para el microservicio Bosques

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#53]
## Descripción:
Crear y configurar la base de datos para los datos del microservicio de la sección de Bosques:

- [ ] Crear la base de datos
- [ ] Crear usuario
- [ ] Documentar proceso genérico para próximos microservicios (Script sql)

### Resultado:
Base de datos creada y configurada, lista para recibir los datos.

**Comment by cazapatamar** [comment]
Documento de referencia: https://docs.google.com/document/d/18Udk8PQufTzckiRH3T4I86uaREspQkoFNWvp-qtgWzw/edit

**Comment by Trjegul84** [comment]
Se actualizó Gitlab con las instrucciones y pasos efectuados. Ver el readme de Biotablero/database.
