### ISSUE TITLE
Cargar los datos de la Sección 2: Integridad de Bosques

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#54]
## Descripción:
Cargar la capa proporcionada por el equipo temático para la sección 2.

### Resultado:
La información necesaria para la presentación de la sección 2: Integridad de bosques cargada y lista en la base de datos correspondiente.

**Comment by cazapatamar** [comment]
Importar capa en bd relacional: https://docs.google.com/document/d/1pZocsyMaJAlt4pf7_E6zRGCgRt2tGSlB_EdFqLFfb7w/edit
