### ISSUE TITLE
Spike: Herramientas para manejo de monorepos

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#56]
## Descripción:
Investigar y revisar herramientas que puedan ser de utilidad para manejar monorepos.

### Resultado:
Definición de herramienta(s) a utilizar.

**Comment by erikasv** [comment]
@cazapatamar @Trjegul84 Bueno, ya hice lo de adaptar el proyecto a un monorepo, no creé un documento porque creo que es muy específico para "convertirlo" y no como cuando se va a crear uno desde 0, los pasos que seguí fueron los siguientes:

1. Antes de seguir los pasos de instalación me aseguré que el nvm estuviera usando la versión especificada en el proyecto (ejecuté `nvm use` dentro de la carpeta del proyecto)
1. Luego seguí los pasos de instalación [por proyecto](https://yarnpkg.com/getting-started/install#per-project-install), saltándome el paso 2.
1. Luego cambié la configuración para usar [node_modules](https://yarnpkg.com/configuration/yarnrc#nodeLinker) porque todo el tema con [plug'n'play](https://yarnpkg.com/features/pnp) está muy enredado aún.
1. Luego convertí el proyecto en un monorepo agregando las [opciones](https://yarnpkg.com/configuration/manifest/#workspaces) correspondientes en el [package.json](https://yarnpkg.com/features/workspaces/#gatsby-focus-wrapper)

Cosas a tener en cuenta:

1. Eslint y apidoc son dependencias globales y se pueden ejecutar a nivel de cada [workspace](https://yarnpkg.com/getting-started/qa#how-to-share-scripts-between-workspaces)
1. Para que lo anterior funcione tuve que agregar el plugin [plugin-workspace-tools](https://yarnpkg.com/api/modules/plugin_workspace_tools.html)
1. Creé un script para generar la documentación global de todo el backend en el package.json de la raíz

Para uds actualizar el proyecto:

1. Instalar yarn globalmente (teniendo en cuenta lo de la versión de nvm)
1. En la carpeta del proyecto ejecutar `yarn install`
1. Revisar los comandos actualizados para las demás cosas

Adicionalmente tuve que deshabilitar la regla en el action de github que verifica que los docs no se hayan actualizados, por los cambios de carpetas que hubo. La idea es habilitarla nuevamente en la próxima tarea (esto lo voy a poner también en esa tarea)
