### ISSUE TITLE
ETL for Páramo shape file

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#6]

**Comment by uamoreno** [comment]
Three Shape files for years 2002, 2009 and 2012 were loaded into geo_paramo_details table, this table are going to be fixed according to naming standars used across the project, the biome id must be fixed as it does not corresponds to ids used on BioTablero, and a new attribute for area: primary, secondary or transform must be set.

**Comment by uamoreno** [comment]
Several DML and DDL were executed in order to fix column names in geo_paramo_details and use existing ids on the BioTablero tables:

	update geo_paramo_details set protected='Quebrada Honda y Canos Parrado y Buque' where protected='Quebrada Honda';
	alter table geo_paramo_details add column id_protected_area int default null;
	alter table geo_paramo_details add column id_biome_fix int default null;
	alter table geo_paramo_details add column area_type varchar(1) default null;
	
	update geo_paramo_details set id_protected_area=foo.gid 
	from (select geo_protected_areas.* from geo_protected_areas) as foo
	where foo.name=geo_paramo_details.protected;
	
	alter table geo_paramo_details drop column id_protect;
	alter table geo_paramo_details drop column protected;
	alter table geo_paramo_details drop column category_p;
	alter table geo_paramo_details drop column date_resol;
		
	update geo_paramo_details set id_biome_fix=foo.gid 
	from (select * from geo_biomes) as foo
	where foo.name=geo_paramo_details.biome
	and id_biome_fix is null;
	
	update geo_paramo_details set id_biome=id_biome_fix;
	alter table geo_paramo_details drop column id_biome_fix;
	alter table geo_paramo_details drop column biome;
	
	update geo_paramo_details set area_type='N' where cover like '3.%' or cover like '5.%' or cover like '4.%';
	update geo_paramo_details set area_type='S' where cover like '2.%';
	update geo_paramo_details set area_type='T' where cover like '1.%';

	alter table geo_paramo_details rename column id_departm to id_sate;
	alter table geo_paramo_details rename column id_municip to id_municipality;
	alter table geo_paramo_details rename column category_ma to category;
	alter table geo_paramo_details rename column name_ecosy to name;
	alter table geo_paramo_details rename column year_ecosy to year;

This issue helps to bring an approach to the methodology for the next ecosystem's uploads. #11
