### ISSUE TITLE
Definir la librería a utilizar para la captura de polígono desde el front-end

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#60]

**Comment by danflop** [comment]
Por el momento se definió que se continuará usando leaflet y un plug-in como leaflet-draw para esta tarea. Sin embargo, esto puede cambiar de acuerdo a los avances en la definición de la solución para la captura y operación sobre los polígonos.

**Comment by Trjegul84** [comment]
Se realizo el spike de revisión de librerías para manejo de mapas y polígono. La presentación se encuentra en el drive:

[``](https://drive.google.com/file/d/10U_YbM7k-zHNcXZWuTDwKRhSYH9h-afZ/view?usp=sharing)
