### ISSUE TITLE
Realizar despliegue de BioTablero con cambios de sección Bosques

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#61]
- Servicio backend: Incluir o descartar hotfix y cambios en producción
- Servicio bosques: Estaría listo para desplegar, pero al estar en el mismo repositorio del backend se debe decidir primero lo del hotfix.
- Front: Bloqueado por el bug [409](https://github.com/PEM-Humboldt/biotablero-frontend/issues/409)
- Gateway: Listo para desplegar

**Comment by erikasv** [comment]
Inspeccionando más a fondo el estado actual de producción se concluye que el hotfix no está aplicado en el backend, por las siguientes razones:

- Los cambios están aplicados directamente sobre producción, ya que se están en el tag 1.3.0 y las diferencias son las mismas que se reflejan en la rama en [GitHub](https://github.com/PEM-Humboldt/biotablero-backend/compare/master...hotfix/1.3.1)![3.png](https://images.zenhubusercontent.com/5c422ae4116ade5d16d9d397/c5a78844-7f70-4d96-9f89-2aa5b1f5a84e)
- Estos cambios se usaron para crear una nueva imagen (1.3.1) ![4.png](https://images.zenhubusercontent.com/5c422ae4116ade5d16d9d397/868969b8-dae9-4f8a-b951-b333413a5c3d) pero el contenedor está corriendo con la 1.3.0 ![2.png](https://images.zenhubusercontent.com/5c422ae4116ade5d16d9d397/ea702b9a-ddb1-4616-bfd7-776316086932)
- Al interior del contenedior, el package.json tiene el script "start-prod" sin el cambio de memoria ![5.png](https://images.zenhubusercontent.com/5c422ae4116ade5d16d9d397/abeb7198-9c1a-4422-b966-4b3677bfda39) y el proceso tampoco lo refleja ![1.png](https://images.zenhubusercontent.com/5c422ae4116ade5d16d9d397/0119e691-238d-415b-be84-030873561b94)

Recomiendo descartar el hotfix y borrar la rama de github

**Comment by erikasv** [comment]
@danflop Lo que sí hay aplicado son todos los cambios del nginx:
![1.png](https://images.zenhubusercontent.com/5c422ae4116ade5d16d9d397/947c7c9b-3c61-44ab-b8a3-d0046100193a)
