### ISSUE TITLE
Revisión de scripts y archivos necesarios para el despliegue de BioTablero

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#62]
Verificar que los Dockerfile, docker-compose, etc, estén funcionando bien y listos para el despliegue.

Como parte de esta tarea se creará el nuevo release en los repositorios y en ella hay que hacer las siguientes correcciones:

- [x] Si el backend retorna un arreglo vacío, enviar un arreglo vacío a la creación del gráfico de integridad
- [x] Los números no se están formateando en la sección de integridad
- [x] Los números de los porcentajes en la barra de áreas protegidas no se están mostrando (se muestra NaN%)

**Comment by erikasv** [comment]
Se crearon las ramas release en los siguientes repositorios:

- [Frontend](https://github.com/PEM-Humboldt/biotablero-frontend/tree/release/1.6.0)
- [Backend](https://github.com/PEM-Humboldt/biotablero-backend/tree/release/1.4.0)
- [Gateway](http://192.168.11.78/pem/biotablero_gateway/tree/release/1.0.0)

Adicionalmente se actualizó la el repositorio de BioTablero del gitlab.
