### ISSUE TITLE
Crear base de datos para el microservicio de conectividad.

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-scrum#65]
- [x] Crear Base de datos de conectividad
- [x] Documentar credenciales de acceso
- [x] Subir datos de conectividad a la base de datos de desarrollo
- [x] Actualizar documentación del modelo ER
- [x] Actualizar instrucciones de despliegue en Gitlab

**Comment by Trjegul84** [comment]
Se creo la base de datos llamada **biotablero-connectivity** en contenedor desarrollo y las credenciales de acceso se encuentran en documento del drive:
[Base de datos - Microservicios](https://docs.google.com/document/d/18Udk8PQufTzckiRH3T4I86uaREspQkoFNWvp-qtgWzw/edit?usp=sharing)

**Comment by Trjegul84** [comment]
Se cargaron 6 tablas en la base de datos de conectividad con el siguiente número de registros:

1. connectivity  -> 2150 
2. connectivity_dpc  -> 2529
3. geo_conn_paramo  -> 1035
4. geo_conn_tropical_dry_forest  -> 855
5. geo_conn_wetland  -> 2145
6. geo_protected_areas  -> 1126 

Se actualizó el archivo readme de Gitlab para la base de datos de biotablero [Ver Gitlab](http://192.168.11.78/pem/BioTablero/tree/master/database)
