### ISSUE TITLE
Revisar ocurrencia de timeouts en la consulta de capas geográficas en módulo de consultas

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#68]
Poder decidir si los ajustes de tiempos de espera realizados en el nginx de producción del BioTablero están siendo efectivos para la prevención de estos errores de timeouts o se pueden eliminar.

**Comment by erikasv** [comment]
En el diagnostico de esta tarea se logró identificar las siguientes cosas:
- Al consultar la capa de humedales en meta el backend se queda sin memoria
- No se logró reproducir una petición que tomara más de 2 minutos en procesarse en el backend
- La mayoría de las peticiones de capas se responden al rededor de 1 minuto y medio, pero al front le toma 2 minutos extra cargarlas en el mapa
- Después de cargarse al capa de persistencia a veces queda bloqueado el sitio
- Aunque se cancele una petición desde el front, en el backend se procesa
