### ISSUE TITLE
Spike: Enviar solicitud de cancelar peticiones al backend

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#71]
Actualmente cuando en el front se cambia de componente y no se ha terminado la petición para cargar una capa, se cancela esta petición, pero a nivel de backend la consulta sigue realizandose, la idea es buscar si se puede interrumpir dicha petición en el backend para evitar consumir recursos.

**Comment by Trjegul84** [comment]
Se encontró un comando de postgres (pg_terminate_backend) para terminar las consultas, pero requiere del id de la consulta para poder terminarla. Exige que se tenga un rastreo de las consultas que se realizan y saber exactamente cuales cancelar.
Estas son las consultas ejemplo:

`  SELECT * FROM pg_stat_activity WHERE state = 'active';  ` So you can identify the PID of the hanging query you want to terminate, run this:
`  SELECT pg_cancel_backend(PID);`  This query might take a while to kill the query, so if you want to kill it the hard way, run this instead:
 ` SELECT pg_terminate_backend(PID);`

**Comment by erikasv** [comment]
Optamos por la solución encontrada el 14 de mayo de 2021, en caso de proceder a implementarla se creará otra tarea para esto.
