### ISSUE TITLE
Desplegar versión de prueba de BioTablero con sección Conectividad de Áreas Protegidas

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#73]

**Comment by Trjegul84** [comment]
Se desplegó una replica del Biotablero con el código de la rama release/1.7.0 (frontend) release/1.5.0 (backend) para que el equipo temático pueda realizar verificaciones y pruebas de los últimos cambios implementados.

El despliegue se encuentra en:  http://192.168.11.58:5000/

@danflop envió un correo al equipo temático notificando la disponibilidad del recurso y solicitando revisiones.

**Comment by Trjegul84** [comment]
Se creo un documento con la descripción del proceso para replicar biotablero en un servidor diferente al de producción con el propósito de realizar pruebas y revisiones antes de efectuar un release. 
El documento se encuentra en [Documento despliegue de entorno de pruebas](https://docs.google.com/document/d/1ylTZVl3wqCANIyH1WwjMndlm_v1rsFQ2MibHGOCL_jc/edit?usp=sharing)

**Comment by Trjegul84** [comment]
Se corrigen las instrucciones de despligue de Biotablero en entorno de pruebas de acuerdo a las sugerencias y se re-ubica  el documento dentro del drive:

[Documento despliegue de entorno de pruebas](https://docs.google.com/document/d/1ylTZVl3wqCANIyH1WwjMndlm_v1rsFQ2MibHGOCL_jc/edit?usp=sharing)

Se actualizan las instrucciones del gateway y de BioTableo en el repositorio de GitLab. Ver cambios en:

[biotablero_gateway](http://192.168.11.78/pem/biotablero_gateway)

[BioTablero](http://192.168.11.78/pem/BioTablero)

**Comment by Trjegul84** [comment]
Se actualizó la rama release/1.7.0 en el servidor .58 de pruebas con los cambios realizados de acuerdo a las solicitudes del equipo temático.
