### ISSUE TITLE
Construir documentos de visualización y datos de la pestaña especies.

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#74]
Generar plantillas para documentos de visualización y datos de acordeón principal

Generar 2 documentos (Riqueza y Vacíos, Diversidad funcional) y compartirlos con Jaime y César para que lo llenen.

**Comment by cazapatamar** [comment]
Se generaron plantillas y documentos de los riqueza y diversidad funcional:

- [Plantillas](https://drive.google.com/drive/folders/19LIJNkulFpIRb2VeCdxIeVVj-4tDlYzg?usp=sharing)
- [Riqueza](https://drive.google.com/drive/folders/1EmG5ceGXINFIOQryNHtjLysDvzcXRQsS?usp=sharing)
- [Diversidad Funcional](https://drive.google.com/drive/folders/1lNfYt80xyB9yFKvdIyqrds6m7O8JZlTC?usp=sharing)
