### ISSUE TITLE
Sipke: Descarga de datos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#76]
Buscar opciones para manejar la descarga de datos de las gráficas, algunas opciones contempladas son (pero no se limitan a estas):

- Implementar descargas desde el backend (como está para las estrategia de compensaciones), tener en cuenta la authenticación que require el gateway, esto probablemente implique crear urls de descarga temporales
- Implementar la descarga desde el front reutilizando los datos que se hicieron para construir la gráfica (implicaría no agregar columnas extra a la descarga)
- Algunas librerías de gráficas ya tienen la funcionalidad empotrada, se podría ver cómo funciona o si vale la pena utilizar otra más

**Comment by Trjegul84** [comment]
Se revisaron diferentes librerías para la descarga de archivos en el front-end entre ellas:

-  react-csv-downloader
-  react-csv
-  react-json-csv

La que finalmente funcionó con éxito fue ***react-json-to-csv*** y se creó la rama **spikeDownload** para que puedan ver el funcionamiento. Con esta librería se toma el mismo json que se resulta de la petición que se hace para construir la gráfica y se convierte en csv que se puede descargar. Si la información que se quiere descargar es diferente de la de las gráficas es necesario realizar otra petición al backend para obtener el json adecuado y no usar el json en la gráfica sino solo en el componente de descarga, sino otra opción es con la misma petición transformar en el front el json de respuesta para adaptar a los campos que se requieren en el archivo csv.   

Se investigó sobre JWS (json web tocken) como una alternativa para la descarga con autenticación pero para implementar esto con express gateway una forma de incluir en las peticiones del backend y crear los tokens pero adaptando a la forma en como tenemos el gateway ahora y lo más probable es que sea necesario crear un plugin que requerirá mucho más esfuerzo.

**Comment by erikasv** [comment]
Con un poco más de investigación sobre la alternativa del JWT en express gateway, llegamos a la conclusión de que no es necesario implementar un plugin sino configurar bien el de JWT, sin embargo es un poco confuso y requiere de tiempito para su apropiado entendimiento y aplicación
