### ISSUE TITLE
Subir datos definitivos de conectividad (Desarrollo y producción)

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-scrum#79]
Subir datos definitivos de conectividad. Jaime dice que para el lunes 3 de mayo ya están completos.

Revisar que no hayan valores NA

Revisar tipos de datos para que correspondan a los que están actualmente en la bd de desarrollo

Subir datos a base de datos de producción

**Comment by Trjegul84** [comment]
Se cargaron los datos actualizados de conectividad, que entregó Jaime, en la base de datos de desarrollo. Se realizaron ajustes manuales porque al importar la capa desde Qgis al final de la carga se presenta el error: 

> 
db_manager.db_plugins.plugin.DbError: SQL error: CREATE INDEX "sidx_geo_conn_tropical_dry_forest_geom" ON "public"."geo_conn_tropical_dry_forest" USING GIST("geom") returned 0 [could not receive data from server: Software caused connection abort (0x00002745/10053) ] ..

![error_qgis_carga_wetland_conectividad.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/8acc6781-cba0-4e6b-943f-25b7f3a11926)

El error ocurre en la creación de indice espacial, entonces se crea este indice por línea comandos.

De igual forma, se creo la base de datos biotablero-connectivity en producción y se realizó el pg_restore con los datos previamente cargados en desarrollo.

Las credenciales de acceso a las bases de datos de los dos entornos, se encuentran en el documento del drive "Crear una base de datos vacía - Microservicios".
