### ISSUE TITLE
[Spike] New Graphics

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#8]
Consultas

- Area (percentage and Ha). per strategic ecosystems
- Ecosystem % per Protected area.
- Cover type (Natural and transformed).

Ecosistemas Estratégicos

- National area (Ha & %)
- Cover change
- % in protected areas.

**Comment by alegnaaived** [comment]
Chord diagram VX + Adjustment for interaction: 
- Goal: https://bost.ocks.org/mike/uberdata/
- Source: https://vx-demo.now.sh/chord + (interaction model like https://vx-demo.now.sh/heatmaps)

**Comment by alegnaaived** [comment]
Radar:
- Goal: http://bl.ocks.org/nbremer/6506614
- Source: https://vx-demo.now.sh/radar

**Comment by alegnaaived** [comment]
Scatter:
https://www.d3-graph-gallery.com/connectedscatter

**Comment by alegnaaived** [comment]
Mixing https://www.d3-graph-gallery.com/graph/connectedscatter_legend.html & https://www.d3-graph-gallery.com/graph/line_change_data.html
Checking http://indicadores.humboldt.org.co/dashboard/ for inspiration

**Comment by alegnaaived** [comment]
Due to the kind of variables, we can just work with graphs focused on categorical variables, like histogram or pie chart. If we involved another variable, like time, we could use the LinearFiltered.jsx component developed.

**Comment by danflop** [comment]
Graphs order:

1. % Ha - Ecosistemas Estratégicos
2. % Ha - Áreas protegidas
3. Coverage
