### ISSUE TITLE
Crear rama de Staging en el repositorio de BioTablero en GitLab

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#83]
- [x] Agregar los últimos cambios que se aplicaron en el último despliegue del ambiente Staging.
- [x] Depurar la rama Master dejando sólo lo que se utilice.

**Comment by Trjegul84** [comment]
Se actualiza el repositorio GitLab. En la nueva rama staging se encuentra la configuración solo con los cambios necesarios para el despliegue del pre-release en server .58
