### ISSUE TITLE
Despliegue ambiente Develop para BioTablero

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-scrum#84]
De acuerdo a este [diagrama](https://drive.google.com/file/d/10siFglQgeb7ybWUEOGfkjN9VQOfHENKW/view?usp=sharing): 

- [x] Crear la rama Develop en el repo de BioTablero en GitLab.
- [x] Generar el Docker Compose de este ambiente.
- [x] Desplegar el ambiente en el servidor asignado.

**Comment by erikasv** [comment]
El ambiente de desarrollo quedó listo, el gateway quedó en `http://192.168.11.58:8383`.

El gateway sólo responde a `localhost:3000` así que no cambien el puerto del front.

@CAScgutierrez esa es la url de la variable `REACT_APP_BACKEND_URL` en la configuración del front (archivo `.env.local`)
