### ISSUE TITLE
Despliegue

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#85]
Desplegar los componentes de BioTablero:

Aplica para cada componente (backend, frontend, gateway)

1. Crear los PR a develop y master de la rama release.
1. **Resolver conflictos con master**
1. **Mezclar en master (previa aprobación)**
1. Resolver conflictos con develop
1. Mezclar en develop (previa aprovación)

1. Actualizar producción (los 3 componentes)

Después de actualizar producción se debe acutalizar el ambiente de staging para qeu se ubique en la rama develop

**Comment by Trjegul84** [comment]
Se efectuaron los pasos y se procedió con el despliegue de la nueva versión del front, back y gateway en producción.

**Comment by Trjegul84** [comment]
Se actualizaron ramas develop incluyendo los cambios de ramas release. 
Se actualizo la rama master de el repositorio BioTablero de GitLab
