### ISSUE TITLE
Cargar datos de número de especies a base de datos de pruebas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#88]
- [x] Crear base de datos de diversidad, usuario, etc
- [x] Documentar credenciales de acceso
- [x] Subir datos de número de especies a la base de datos del ambiente de desarrollo
- [x] Actualizar documentación del modelo ER
- [x] Actualizar instrucciones de despliegue en Gitlab

Jaime nos debe entregar los datos en la forma expuesta en el [documento](https://docs.google.com/document/d/10lNRDshhzXKYIexWcxSsixPpKW85QzafwztcKUpL4nw/edit#heading=h.rr2d7r4ra2ek)

## Consideraciones
- Si los datos se entregan a más tardar el 15 de junio, se incluye en el mismo sprint la tarea de la implementación de los endpoints
- Si los datos se entregan después del 21 junio, esta tarea se mueve para el siguiente sprint.
- La carga de los raster se tendrá en otra tarea

**Comment by cazapatamar** [comment]
- Los datos quedaron cargados en la base de datos de desarrollo
- Se actualizaron los tipos de datos para no tener problemas al hacer las consultas. El script usado quedó en el drive
- Se actualizó el documento de diccionario de datos de acuerdo a la estructura final entregada por Jaime
