### ISSUE TITLE
Más pruebas con raster

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#90]
Jaime va a enviar más raster de diferentes tamaños y resoluciones para poder realizar las siguientes pruebas:

- Qué tan pesado resulta traer las imágenes desde postgis
- Si se puede mejorar la "pixelación" de los colores en el geoserver

**Comment by erikasv** [comment]
En el caso de postgis se cargó con éxito el raster de 300m y el tiempo de respuesta en la consulta está por debajo de los 2 segundos, el tamaño de la imagen aumentó de 85kb a 432kb para el departamento del meta, aunque sigue siendo un tamaño manejable.

El raster de 30m hubo que cargarlo fraccionado y no logré hacer la intersección con la geometría deseada (la consulta retorna null) pero todas las consultas se demoran más de 4 minutos, tiempo inadmisible.

**Comment by cazapatamar** [comment]
Se realizó la carga de los raster a 300M (int y float) al geoserver. Los de 30 no pudieron ser subidos por que al parecer geoserver no trabaja muy bien con el formato .img. Se adjuntan pantallazos para poder comparar las 3 alternativas que tenemos hasta el momento:

Raster original:

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/319b9c2a-f327-488c-964a-cc90f9b676b4)

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/26a8680b-af3d-45a6-9749-cb6dc33ded50)

Raster 300M int:

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/bd429f45-4547-42fd-bbaa-eee5ebf8d172)

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/9f4fda70-990d-4253-b41b-e2e23542ff5e)

Raster 300M float:

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/17e698b1-7f70-409d-8f88-d692cf8dce03)

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/4dd88d22-b6d7-4517-980f-3d21d69e41ae)
