### ISSUE TITLE
Actualizar ambiente de staging

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#92]
Hay que crear la rama del próximo release y desplegar el ambiente de staging.

1. Crear rama release en los 3 repos
1. Desplegar la rama en el .58 como quedó estipulado para el ambiente

**Comment by Trjegul84** [comment]
Se crearon las ramas release en los tres repositorios.
Se desplegó el ambiente de _staging_ con los avances en la sección número de especies.

El ambiente de _staging_ queda en la carpeta BioTablero y el ambiente de _develop_ en carpeta BioTablero_dev.

Respecto a los nombres de los contenedores se mantiene el mismo formato biotablero_nombreservicio_back para todos los servicios de staging y únicamente se agrega parte diferenciadora para las gateways, donde se tiene identificadores `_stag` y `_dev` 

El contenedor de ambiente develop _biotablero_diversity_dev_ fue borrado siguiendo lo acordado en la reunión de hoy (26 de Julio de 2021).
