### ISSUE TITLE
Actualizar raster de Número de especies

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#93]
Actualizar los raster cargados del número de especies, debido a que se encontraron errores en la capa de endémicas. Jaime nos entregará las nuevas.

Se entregarán los datos como máximo el 24 de Septiembre.

**Comment by cazapatamar** [comment]
Se actualizó el raster de endémicas en la base de datos de pruebas. Se nota que de acuerdo a cómo se asignan los colores en la consulta, los valores 0 o nulos no se pintan.

Se consulta con Jaime y se determina que los valores 0 hacen parte de la escala por lo que es necesario cambiar la consulta en el back.
