### ISSUE TITLE
Spike: Carga de geometrías sobrepuestas

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#95]
Solicitar a Jaime el ejemplo de capas sobrepuestas y cargarlas a postgis para verificar que no haya ningún inconveniente

**Comment by cazapatamar** [comment]
Se cargo la capa de prueba de manera local y en la bd de pruebas en el 106. Ambos casos fueron exitosos

La tabla se llama `geo_forest_lp`
