### ISSUE TITLE
Spike: Cargar raster de 90m

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#96]
Jaime nos va a pasar un raster a 90m para cargarlo en una tabla en postgis y ejecutar la consulta que quedó implementada para el número de especies, analizar los resultados y tiempos de la consulta.

Esta tarea es continuación de la #91 con el fin de verificar la resolución más alta que pueda manejar postgis

**Comment by cazapatamar** [comment]
Se subió el raster a 90 metros y se obtiene los siguientes tiempos de respuesta:

**EA - CARDER**

- 192.168.11.106
&nbsp; - Insomnia: 2.65 s
&nbsp; - Biotablero front:  2.109 s

- Localhost
&nbsp; - Insomnia: 0.89 s
&nbsp; - Biotablero front:  1.01 s

**STATE - META (50)**

- 192.168.11.106
&nbsp; - Insomnia: 38.8 s
&nbsp; - Biotablero front: 37  s

- Localhost
&nbsp; - Insomnia: 15 s
&nbsp; - Biotablero front:  16.32 s

**EA - CORPORINOQUIA**

- 192.168.11.106
&nbsp; - Insomnia: 101 s
&nbsp; - Biotablero front:   s

- Localhost
&nbsp; - Insomnia: 32.2 s
&nbsp; - Biotablero front:  36.3 s
