### ISSUE TITLE
Spike: Probar otro tipo de almacenamiento para los raster

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-scrum#98]
Las pruebas que se han realizado para consultar datos por ingreso de polígono sobre raster en postgis no han sido muy buenas. Explorar si hay otra herramienta (tipo de almacenamiento) que nos permita hacer consultas de este tipo y realizar pruebas sobre esta.

**Nota**: Ya se exploró la consulta usando GeoServer y tampoco tiene tiempos satisfactorios

**Comment by alegnaaived** [comment]
https://koopjs.github.io/docs/basics/what-is-koop ¿podría ser?

**Comment by erikasv** [comment]
Se ha decidido crear una instancia del stac catalog, en caso de que se tenga demasiada prioridad se podrán usar archivos [cog](https://www.cogeo.org/)
